### ISSUE TITLE
Error with `flutter_outline` enabled

### ISSUE THREAD

**Issue by BenoitPingris** [akinsho/flutter-tools.nvim#10]
Hi,
with the option `flutter_outline` enabled, I have this error message that shows up when I insert a new line under a widget for example:
```
Error executing vim.schedule lua callback: ...s/start/flutter-tools.nvim/lua/flutter-tools/outline.lua:484: attempt to perform arithmetic on local 'index' (a nil value)  
```

Here's my configuration for `flutter-tools`:
```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

require("flutter-tools").setup {
  flutter_outline = {
    enabled = true
  },
  lsp = {
    capabilities = capabilities
  }
}
```
This message only appears if I edit lines where the outline is visually set.

I used the starter flutter project to test it.

Thanks!

**Comment by akinsho** [comment]
Hi @BenoitPingris thanks for trying out the plugin and reporting the issue 👍🏿. Yep can easily reproduce it and have a fix for it.
