### ISSUE TITLE
[Bug]: Error in dap_runner when flutter is started

### ISSUE THREAD

**Issue by sidlatau** [akinsho/flutter-tools.nvim#109]
**Describe the bug**

I am testing new feature when DAP is started  automatically when running `:FlutterRun`. App is started but I am getting this error:
```
Error executing vim.schedule lua callback: ...tter-tools.nvim/lua/flutter-tools/runners/dap_runner.lua:68: table index
 is nil
```

**To Reproduce**
My setup (I am using LunarVim):
```lua
	{
		"akinsho/flutter-tools.nvim",
		requires = "nvim-lua/plenary.nvim",
		config = function()
			require("flutter-tools").setup({
				lsp = {
					on_attach = function(client, bufnr)
						require("lvim.lsp").common_on_attach(client, bufnr)
					end,
					capabilities = require("lsp-status").capabilities,
				},
				debugger = { 
					enabled = true,
					run_via_dap = true,
				},
				fvm = true,
				widget_guides = {
					enabled = true,
				},
			})
			require("telescope").load_extension("flutter")
		end,
	},

```

**Expected behavior**
I expect no error messages.

**Screenshots**

**System information**

- OS: MacOS
- Flutter version: 2.5.3
- Is flutter in $PATH: yes
- neovim version: 0.5.1

**Comment by akinsho** [comment]
Hi @sidlatau,

I haven't encountered this issue in my usage and can't reproduce it. Do you definitely have the debugger installed and running?. @clement-buchart any ideas seems to be here:
 https://github.com/akinsho/flutter-tools.nvim/blob/6acf7d2ed2aeebf932808e99e64a4f71fe508606/lua/flutter-tools/runners/dap_runner.lua#L68

**Comment by clement-buchart** [comment]
Hum it's stange, all code path seem to check that extensionRPC is not null in https://github.com/Dart-Code/Dart-Code/blob/master/src/debug/dart_debug_impl.ts 

It's safer to check for nullity on our side too. I opened PR https://github.com/akinsho/flutter-tools.nvim/pull/110 to make this safer. 

@sidlatau you can get all the events to be logged by following instructions at https://github.com/mfussenegger/nvim-dap/blob/master/doc/dap.txt#L668
It would be great to see the event that trigger the error

**Comment by sidlatau** [comment]
Looks like https://github.com/akinsho/flutter-tools.nvim/pull/110 did the trick - I am unable to reproduce the bug and debug with hot-restart works! Thanks, @clement-buchart !

One more (unrelated) question - I do not understand what format should be used there:
```lua
require("dap").configurations.dart = {
        <put here config that you would find in .vscode/launch.json>
      }
```

I have this launch configuration, but it is JSON, I can not put it in lua config:
```json
{
    "configurations": [
    {
        "name": "Flutter DEV",
        "type": "dart",
        "request": "launch",
        "program": "lib/main.dart",
        "flutterMode": "debug",
        "args":[
            "--dart-define=flavor=dev",
            "--flavor",
             "dev"
        ]
    },
    {
        "name": "Flutter PROD",
        "type": "dart",
        "request": "launch",
        "program": "lib/main.dart",
        "flutterMode": "debug",
        "args":[
            "--dart-define=flavor=prod",
            "--flavor", 
            "prod"
        ]
    }
    ]
}
```

**Comment by clement-buchart** [comment]
You can use `vim.fn.json_decode(some_json_string)` to decode JSON as a lua table.
You can see how nvim-dap source launch.json file for example : https://github.com/mfussenegger/nvim-dap/blob/66842e08402ee0e9d6a3dd50e5cb753bfac288dd/lua/dap/ext/vscode.lua#L7-L18

Note that if you work on a project that uses `.vscode/launch.json` you can use that directly by using something like this config : 
```
require("flutter-tools").setup {
  debugger = {
    enabled = true,
    run_via_dap = true,
    register_configurations = function(_)
      require("dap").configurations.dart = {}
      require("dap.ext.vscode").load_launchjs(require("flutter-tools.lsp").get_lsp_root_dir() .. "/.vscode/launch.json")
    end,
  },
......
```

**Comment by sidlatau** [comment]
@clement-buchart thanks for the explanation and thanks for this feature!
