### ISSUE TITLE
[Bug]: Cannot scroll in hover doc anymore 

### ISSUE THREAD

**Issue by Kisto17** [akinsho/flutter-tools.nvim#115]
**Describe the bug**
The scroll in hover doc working for me so far until this morning after updated the plugin. I believed the issue is from dartls come with this plugins because if I uninstall this plugin, install just dartls, hover doc can even use keyboard to navigate but after uninstall dartls, install flutter-tools and using the language server come with it, just the mouse working when I want to scroll. And until now the mouse seems like unavailable too.

**System information**

- OS: archcraft
- Flutter version: 2.8.1
- Is flutter in $PATH: Yes
- neovim version: 0.6.1

**Comment by akinsho** [comment]
@Kisto17 I'm not sure exactly what the problem you're referring to is. On my end I cant see any issue with the hover doc window when I try to move around within it. This plugin has nothing to do with the mouse behaviour in a user's nvim and doesn't change or touch any mouse related behaviour

**Comment by Kisto17** [comment]
Thanks you so much for taking your time answer me, I'll close this report.
