### ISSUE TITLE
[Bug]: LSP not starting for dart-only projects

### ISSUE THREAD

**Issue by nank1ro** [akinsho/flutter-tools.nvim#116]
First of all thank you a lot for this plugin.
I'm coming from `coc, coc-flutter` and I have to say that with `nvim-lsp-config` and your plugin everything is faster.

**Describe the bug**
The LSP is not starting for dart-only projects. For flutter projects everything works fine.
I'm using NvChad, and here it is the packer init.lua config about `flutter-tools`:
```lua
use {
    "akinsho/flutter-tools.nvim",
    requires = {
        "mfussenegger/nvim-dap",
        "nvim-lua/plenary.nvim"
    },
    event = "VimEnter",
    config = function()
        require("flutter-tools").setup {
            ui = {
                border = "rounded"
            },
            decorations = {
                statusline = {
                    app_version = true,
                    device = true
                }
            },
            debugger = {
                enabled = true,
                run_via_dap = true,
                register_configurations = function(paths)
                    require("dap").configurations.dart = {}
                    require("dap.ext.vscode").load_launchjs()
                end
            },
            flutter_path = "~/development/flutter",
            flutter_lookup_cmd = nil,
            fvm = true,
            widget_guides = {
                enabled = false
            },
            closing_tags = {
                highlight = "ErrorMsg",
                prefix = ">",
                enabled = true
            },
            dev_log = {
                enabled = false,
                open_cmd = "tabedit"
            },
            dev_tools = {
                autostart = false,
                auto_open_browser = false
            },
            outline = {
                open_cmd = "30vnew",
                auto_open = false
            }
        }
    end,
    
    setup = function()
        require("core.utils").packer_lazy_load "flutter-tools.nvim"
    end
}
```

Inside the `README.md` you said to don't configure `dartls` because it is already being done by this plugin.
In fact, with the Flutter projects all works fine, but when I open a dart-only project the LSP doesn't start.
I've looked inside this plugin code and I noticed that you enable it on all `*.dart` files, so it should work, right?

If this is the expected behaviour, may I know how to configure the `dartls` to start only on non-flutter projects.

**To Reproduce**

1. Go to a Dart-only project with nvim
2. See LSP not starting

**Expected behavior**
Have the LSP working

**System information**
- OS: macOS Monterey 12.1
- Flutter version: 2.8.1
- Is flutter in $PATH: Yes
- neovim version: 0.6.1

**Comment by nank1ro** [comment]
Adding an error that appeared today, when opening a Dart-only project:
```lua
E5108: Error executing lua ...l/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:1154: client_id: exp
ected number, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        ...l/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:1154: in function 'buf_attach_client'
        ...er/opt/flutter-tools.nvim/lua/flutter-tools/lsp/init.lua:190: in function 'get'
        ...er/opt/flutter-tools.nvim/lua/flutter-tools/lsp/init.lua:158: in function 'attach'
        [string ":lua"]:1: in main chunk
        [C]: in function 'cmd'
        ...site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/lib.lua:394: in function 'open_file'
        ...vim/site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree.lua:180: in function 'on_keypress'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'cmd'
        ...site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/lib.lua:394: in function 'open_file'
        ...vim/site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree.lua:180: in function 'on_keypress'
        [string ":lua"]:1: in main chunk
```
I don't know if it's related

**Comment by akinsho** [comment]
Hi @nank1ro,

Thanks for reporting this. Ideally this should also work on dart only projects but tbh I only work with flutter + dart so don't often test in dart only environments. Can you have a look at your lsp logs to see if you have any errors being reported.
You can do this by running the `:edit` command on the file output by running `:lua  vim.lsp.get_log_path()`

**Comment by nank1ro** [comment]
Hi @akinsho thank you for your reply :)
The `lsp.log` simply contains `[START][2022-01-09 20:16:32] LSP logging initiated`, no errors are present.

The command `LspInfo` returns:
<img width="1680" alt="Screenshot 2022-01-09 at 20 18 12" src="https://user-images.githubusercontent.com/60045235/148697303-4db0097f-53d9-4dec-848d-6da804a74416.png">

While for Flutter projects I see that there is 1 attached server

**Comment by akinsho** [comment]
@nank1ro can you confirm that the project has a `.git` folder and also a `pubspec.yaml`?

**Comment by nank1ro** [comment]
@akinsho yes I confim. You can reproduce the issue simply running these commands:
```sh
dart create -t console-full dart-only-proj
cd dart-only-proj
git init
vim lib/dart_only_proj.dart
```

After entering in this project this error happend:
```
Spawning language server with cmd: `~/bin/dart` failed. The language server is either not installed, missing from PATH, or not executable.
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load
.lua:155: Vim(lua):E5108: Error executing lua ...l/Cellar/neovim/0.6.1/share/nvim/runtime/lua/vim/lsp.lua:1154: client_id: expected number, got nil
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```

**Comment by nank1ro** [comment]
Maybe I simply have to put the `dart` bin inside the path used? `~/bin/dart`.
My current dart path is: `/Users/alex/development/flutter/bin/dart`

**Comment by nank1ro** [comment]
I may have an idea about the cause.
If I have `fvm` set to `true` on Flutter projects the error is not presented and the LSP starts.
If I set `fvm` to `false`, also Flutter projects show the same error.

While on Dart projects I cannot setup fvm (it's only for flutter)

**Comment by akinsho** [comment]
@nank1ro do you have `fvm` installed or any of it's files setup somewhere above your project?

**Comment by nank1ro** [comment]
@akinsho yes I have `fvm` installed and in the working flutter projects I see the `.fvm` folder in the root.
While on Dart-only projects cannot be setup and there isn't the `.fvm` folder at the project root.

**Comment by akinsho** [comment]
@nank1ro I think this might be because at least by this plugins standard's your setup is a little complex, I'm guessing that you have flutter installed in a custom directory via fvm maybe in but are using the plugin without fvm in a dart only project since you have to but don't have dart independently installed right i.e. you depend on the dart in the custom flutter install directory in which case this plugin won't have any idea how to resolve the path to your dart bin. You can add in a `flutter_path` manually which might help

**Comment by nank1ro** [comment]
@akinsho if you see the first comment, I already set the `flutter_path` manually to: `flutter_path = "~/development/flutter"`.
I'm going to try to install the Dart SDK directly and I'll let you know if it works

**Comment by nank1ro** [comment]
I've installed dart with brew.
Then copied all the bin content to `~/bin` but still nothing, same error happens.

**Comment by fitrh** [comment]
Hi @nank1ro, I use this plugin as my daily dart-non-flutter development tools to replace my `dartls` configuration and it works
I think your problem is because you are using NvChad with that weird lazy loading
if you want lazy load, I suggest you to use `ft = dart` instead.

Here is my packer spec for this plugin

```lua
{
  "akinsho/flutter-tools.nvim",
  requires = "nvim-lua/plenary.nvim",
  config = function()
    require("plugin.flutter-tools.config")
    require("plugin.flutter-tools.keymap")
  end,
  ft = "dart",
  event = "BufRead pubspec.yaml",
  module = "flutter-tools",
}
```

**Comment by akinsho** [comment]
Going to close
