### ISSUE TITLE
Feat: Reconnect to running flutter process

### ISSUE THREAD

**Issue by joshpetit** [akinsho/flutter-tools.nvim#117]
I'm not sure how possible this is, but it would definitely be very useful. Occasionally you need to exit neovim, reloading config for example. Would it be possible to reconnect to a running flutter process?

I have no experience with this, but would saving the process id let you reconnect to it later? Not sure at all, but this would be cool 😅.

**Comment by akinsho** [comment]
@joshpetit I believe all  processes started by   neovim are closed when it is shut down so if a Flutter process was running and neovim was terminated the process would be killed so could not be resurrected on restart.  Hanging onto the process ID wouldn't work here

**Comment by joshpetit** [comment]
Ahh ok, so the process is killed anyway. Makes sense, thanks!
