### ISSUE TITLE
[Bug]: Lsp is not starting on Windows 10

### ISSUE THREAD

**Issue by erturk** [akinsho/flutter-tools.nvim#126]
**Describe the bug**

On my windows 10 machine, :LspInfo displays 

> 0 client(s) attached to this buffer

When I increase the log level of nvim, it prints this error in the log file: 

> Spawning language server with cmd: `C:\Users\<username>\fvm\versions\stable\bin\dart` failed. The language server is either not installed, missing from PATH, or not executable.

The above file path points to a bash file. 

I had to make the following changes in _flutter-tools\executable.lua:49_ to make it work.
```lua
local function _flutter_sdk_dart_bin(flutter_sdk)
  -- retrieve the Dart binary from the Flutter SDK
  return path.join(flutter_sdk, "bin", "dart.bat") -- I appended .bat extension 
end
```

I have no idea how  to detect if it's running on windows and if so append the .bat suffix.

**To Reproduce**
Lsp is not started when I open a flutter project in neovim with default configurations of this plugin. 
```
require("flutter-tools").setup{ }
```
**System information**

- OS: Windows 10 19043.1466
- Flutter Version
> `flutter --version`
> Flutter 2.10.0 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 5f105a6ca7 (7 days ago) • 2022-02-01 14:15:42 -0800
> Engine • revision 776efd2034
> Tools • Dart 2.16.0 • DevTools 2.9.2

- Neovim version: 0.6.1

**Comment by akinsho** [comment]
@erturk I've encountered a similar issue a while ago from a windows user and asked this question (which they didn't answer unfortunately), should the binary *always* be append with `.bat` for all windows users or is it possible a windows user is using WSL or some other mechanism that doesn't require that extension or it would break for. I don't use windows and have no way of testing on it, I'm happy to change this but don't want to immediately be inundated with bug reports that it broke for someone else. If a windows user can give me a clear description of what the universally correct way there is to resolve this on windows then I'm happy to implement it 🤷🏿

**Comment by erturk** [comment]
I'm not a WSL user and I'm not 100% certain about this but using neovim on a WSL environment is no different to running it on a regular Linux. The OS is Linux in WSL neovim . If it's possible to append the .bat suffix according to detected running OS, it would be a universally correct way, I think.

Thanks for the great plugin.

**Comment by adelarsq** [comment]
@akinsho I'm interested on this. I can help on tests.

**Comment by akinsho** [comment]
OK I've just pushed a change to use `.bat` on Windows hopefully that puts this issue to bed rather than opens up another can of worms in which case I will revert the change and wait for a Windows user to contribute a safer/better solution.

**Comment by adelarsq** [comment]
@akinsho It's working on Windows. At moment I use this plugin just on macOS. I will start using it also on Windows so I provide feedback.
