### ISSUE TITLE
[Bug]: flutter-tools setup fails with Normal hl-group bg color set to "none"

### ISSUE THREAD

**Issue by Sympel** [akinsho/flutter-tools.nvim#127]
**Describe the bug**
My colorscheme sets the Normal background color to "none", which makes the `vim.api.nvim_get_hl_by_name("Normal", true)["background"]` call in your config script (config.lua:100) return `nil`. The config script then fails when it tries to do something with this color.

Error message:
`packer.nvim: Error running config for flutter-tools.nvim: ...flutter-tools.nvim/lua/flutter-tools/lsp/color/utils.lua:66: 
bad argument #1 to 'rshift' (number expected, got nil)`

**To Reproduce**
1. Choose a colorscheme with background color of "Normal" highlight group set to "none"
2. `require"flutter-tools".setup{}` in your config

**Expected behavior**
Flutter-tools should start without errors and use a transparent background color.

**Screenshots**

**System information**

- OS: Archlinux
- Flutter version: 2.10.0
- Is flutter in $PATH: yes
- neovim version: 0.6.1

**Additional context**

**Comment by akinsho** [comment]
@Sympel thanks for reporting this I always forget that some people use transparent terminals so background colors can't be depended on consistently. I'll have a look at that as soon as I get a chance.

**Comment by akinsho** [comment]
I guess you could always specify a `config.lsp.color.background_color` yourself if you want it to work despite having a transparent terminal.
