### ISSUE TITLE
User's configuration is not taken into account when getting sdk path

### ISSUE THREAD

**Issue by nghialm269** [akinsho/flutter-tools.nvim#13]
Hi,
Thanks for the great plugin.

After this commit b5fcd4be053ca75ca00fb66fe24b84db71d415f3, I wasn't able to set my own `flutter_lookup_cmd` anymore.

I tried to put `vim.notify(vim.inspect(_config))` after [this line](https://github.com/akinsho/flutter-tools.nvim/blob/6189733c40b378693bcb730a232b567e26591a9c/lua/flutter-tools/executable.lua#L65), and I don't see my configuration in the output.
I also tried `vim.notify(vim.inspect(require("flutter-tools/config").get()))` there but still not see my configuration.

It seems like the user configuration is lost. I tried to fix it but my lua is not good enough.

My configuration:
```lua
require'flutter-tools'.setup{
  experimental = {
    lsp_derive_paths = true,
  },
  flutter_lookup_cmd = "asdf where flutter",
  flutter_outline = {
    highlight = "NonText",
    enabled = true,
  },
  closing_tags = {
    highlight = "Comment",
    prefix = "-- "
  },
  dev_log = {
    open_cmd = "tabedit",
  },
  outline = {
    open_cmd = "30vnew",
  },
  lsp = {
    on_attach = on_attach,
    capabilities = capabilities,
  }
}
```
(btw there are some typos in the readme: `derive_lsp_paths` -> `lsp_derive_paths`, `asdf which flutter` -> `asdf where flutter`)

**Comment by akinsho** [comment]
@nghialm269 thanks for trying out the plugin 👍🏿 and for pointing this out. I pushed a change which should fix it this morning lemme know how that works. Regarding the typos in the README can you make a PR, there's a lot to do and I easily forget things like that

**Comment by nghialm269** [comment]
> I pushed a change which should fix it this morning lemme know how that works.

Thanks, the commit fixed the configuration issue for me, I found another issue (not sure if it is due to the commit or due to the previous refactor):

if I do `FlutterRun` and then `FlutterQuit`, after that I can't do `FlutterRun` anymore, I get 
![image](https://user-images.githubusercontent.com/13317164/111436286-63f54680-8734-11eb-96e6-1cc45a059370.png)

> Regarding the typos in the README can you make a PR, there's a lot to do and I easily forget things like that

I just created a PR for that: #14

**Comment by akinsho** [comment]
@nghialm269 it could easily be from before or after the refactor I don't think I've actually got that workflow working correctly yet, I need to remove some resources after a user quits which I'm not doing yet. Do you mind raising that as a separate issue I can track and will push a fix when I get a chance. Thanks for testing stuff out btw.

> I just created a PR for that: #14
🎉 👍🏿

**Comment by akinsho** [comment]
@nghialm269 I've raised a separate issue for this in #15 so will close this out now since the latest commit fixed this specific issue
