### ISSUE TITLE
formatting conflict with null-ls

### ISSUE THREAD

**Issue by ravenpdev** [akinsho/flutter-tools.nvim#133]
<img width="644" alt="Screen Shot 2022-02-21 at 11 56 09 PM" src="https://user-images.githubusercontent.com/45135812/154989198-9f924ad4-c934-46d5-880c-9e057390cbd0.png">

Hi, I want to use null-ls to format the code on save. but it ask me to choose which formatter I want to use. I already disabled the  following in the lspconfig
```lua
   client.resolved_capabilities.document_formatting = false
   client.resolved_capabilities.document_range_formatting = false
```

**Comment by br1anchen** [comment]
I have the same setup, in order to apply `dartls` config with `flutter-tools`, you need to pass your lsp config into `flutter-tools` setup method instead of doing them in `lspconfig`:
```lua
-- lspconfig.lua
      if server.name == "dartls" then
         opts.on_attach = disable_lsp_formatting_on_attach
         require("custom.plugins.flutter-tools").setup(disable_lsp_formatting_on_attach, opts.capabilities)
      end

-- custom/plugins/flutter-tools.lua
    function setup(attach, capabilities)
        require("flutter-tools").setup {
            lsp = {
                on_attach = attach,
                capabilities = capabilities,
           },
       }
    end
```

**Comment by ravenpdev** [comment]
Hi @br1anchen 

I did what you sent and it works like a charm.

Thank you,

**Comment by Invincible1996** [comment]
> <img alt="Screen Shot 2022-02-21 at 11 56 09 PM" width="644" src="https://user-images.githubusercontent.com/45135812/154989198-9f924ad4-c934-46d5-880c-9e057390cbd0.png">
> 
> Hi, I want to use null-ls to format the code on save. but it ask me to choose which formatter I want to use. I already disabled the following in the lspconfig
> 
> ```lua
>    client.resolved_capabilities.document_formatting = false
>    client.resolved_capabilities.document_range_formatting = false
> ```

Excuse me. Could you tell me how to use null-ls format flutter code?Thanks!

**Comment by Invincible1996** [comment]
> I have the same setup, in order to apply `dartls` config with `flutter-tools`, you need to pass your lsp config into `flutter-tools` setup method instead of doing them in `lspconfig`:
> 
> ```lua
> -- lspconfig.lua
>       if server.name == "dartls" then
>          opts.on_attach = disable_lsp_formatting_on_attach
>          require("custom.plugins.flutter-tools").setup(disable_lsp_formatting_on_attach, opts.capabilities)
>       end
> 
> -- custom/plugins/flutter-tools.lua
>     function setup(attach, capabilities)
>         require("flutter-tools").setup {
>             lsp = {
>                 on_attach = attach,
>                 capabilities = capabilities,
>            },
>        }
>     end
> ```

Hi@br1anchen.I can't find the server .Could you show me the code?
