### ISSUE TITLE
[Bug]: flutter-tools.nvim/lua/flutter-tools/lsp/color/utils.lua:103: attempt to index field 'priorities' (a nil value)

### ISSUE THREAD

**Issue by sollymay** [akinsho/flutter-tools.nvim#135]
**Describe the bug**

Getting an error when opening a file that has LSP Colors (did not make any changes to my config), but the issue started today

```
Error executing vim.schedule lua callback: ...flutter-tools.nvim/lua/flutter-tools/lsp/color/utils.lua:103: attempt to index field 'priorities' (a nil value)                                                                                                                                        
stack traceback:
        ...flutter-tools.nvim/lua/flutter-tools/lsp/color/utils.lua:103: in function 'hl_range'
        ...flutter-tools.nvim/lua/flutter-tools/lsp/color/utils.lua:128: in function 'color_background'
        ...flutter-tools.nvim/lua/flutter-tools/lsp/color/utils.lua:224: in function 'buf_color'
        ...flutter-tools.nvim/lua/flutter-tools/lsp/color/utils.lua:183: in function 'handler'
        ...w/Cellar/neovim/0.6.0/share/nvim/runtime/lua/vim/lsp.lua:957: in function 'cb'
        vim.lua:285: in function <vim.lua:285>

```
**To Reproduce**

1. Open any .dart file that has one of the LSP Colors, such as Colors.deepOrange, Colors.purple.2. 
2. After opening, highlighting starts working on other options but when it gets to color, the error occurs
3. Colors are not highlighted

**Expected behavior**
Colors should be highlighted and no error should show 

**Screenshots**
<img width="1368" alt="Screen Shot 2022-02-28 at 4 58 28 PM" src="https://user-images.githubusercontent.com/6496698/156065439-a1e3c3cf-22bb-4ff8-bfd1-53f99933de72.png">

**System information**

- OS: MacOS 12.2.1
- Flutter version: 2.10.2
- Is flutter in $PATH: yes
- neovim version: 0.6.0

**Comment by akinsho** [comment]
Thanks for reporting this @sollymay pushed a fixed which should have resolved this
