### ISSUE TITLE
[Question]: Flutter log colouring not working for ANIS colours

### ISSUE THREAD

**Issue by momrak** [akinsho/flutter-tools.nvim#137]
From what I can see from the screenshots in the README it seems as you have working log colorizing. 

How do you achieve that? For me the emojis are showing nicely, but ANSI colour codes are show as is, making the log harder to read.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/6552049/156727314-5e111646-6f15-446d-b362-7ab7cb80e25e.png">

**Comment by rlch** [comment]
I've dabbled around with ANSI colours using [chrisbra/Colorizer](https://github.com/chrisbra/Colorizer), it works okayish, but I have some issues with colours not updating when the buffer isn't active, and it only activates upon initially switching to the window.

```lua
      {
        'chrisbra/Colorizer',
        config = function()
          vim.g.colorizer_auto_filetype = 'log'
          vim.g.colorizer_disable_bufleave = 1
        end,
      },
```

Let me know if you improve this config :)

**Comment by momrak** [comment]
Thanks for the response! Tried that now, but not too happy with the result.. 

Here is a side by side when running `flutter run` from `:term` inside neovim, and the other is the from the log after running `:FlutterRun`. There are apparently other things coloured as well in the one that is run from the terminal. Could it be an idea to run it through a terminal like this instead? Or what are the benefits of having it as a buffer? (I am relatively new to vim/neovim, so this might be a stupid question :) )
Is this something that could be configured from?
```
  dev_log = {
    enabled = true,
    open_cmd = "tabedit", -- command to use to open the log buffer
  },
```

<img width="1862" alt="image" src="https://user-images.githubusercontent.com/6552049/156730061-a3cafab4-d735-4bf8-9436-c8c0557da9a8.png">

**Comment by akinsho** [comment]
Hi @momrak, so I've explicitly chosen to have the flutter dev log buffer be a normal buffer because I can be in control of how it renders I haven't fully taken advantage of it yet though but plan to in the long run to do things like highlight file URLs etc.

Anyway regarding how to improve the rendering the buffer is actually set to a file type of `log` and there are plugins to syntax highlight log files such as https://github.com/MTDL9/vim-log-highlighting.

**Comment by momrak** [comment]
I see. Thank you for the reply
