### ISSUE TITLE
[Bug]: can't open devtools when running via dap

### ISSUE THREAD

**Issue by albinpk** [akinsho/flutter-tools.nvim#139]
**Describe the bug**

Flutter DevTools not opening when running via `dap`

##### Error shows on cammand `:FlutterDevTools`

```
Error executing vim.schedule lua callback: ...start/flutter-tools.nvim/lua/flutter-tools/dev_tools.lua:134: bad argument #1 to 'ipairs'
(table expected, got string)
stack traceback:
        [C]: in function 'ipairs'
        ...start/flutter-tools.nvim/lua/flutter-tools/dev_tools.lua:134: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
Press ENTER or type command to continue

```

**Screenshots**
###### Running `:FlutterDevTools` after `:FlutterRun`

![Screenshot_2022-03-16_20-49-10](https://user-images.githubusercontent.com/56157868/158626764-62be99a0-ae00-40d5-aa58-75210cad2cf3.png)

**System information**

- OS: **Linux arch 5.15.28-1-lts**
- Flutter version: **Flutter 2.10.3 • channel stable • Dart 2.16.1 • DevTools 2.9.2**
- Is flutter in $PATH: **Yes**
- neovim version: **v0.6.1**

**Additional context**

- flutter-tools config
```lua
require("flutter-tools").setup({
-- ...

  debugger = {
    enabled = true,
    run_via_dap = true, 
  },

-- ...
})

```

**Comment by aridgupta** [comment]
I am facing the same issue. Is there anyway to fix this?

**Comment by sidlatau** [comment]
This should be already fixed.
