### ISSUE TITLE
[Question] Flutter Run opens __FLUTTER_DEV_LOG__ buffer but also opens a new tab with same buffers. Why?

### ISSUE THREAD

**Issue by dastagg** [akinsho/flutter-tools.nvim#140]
This might not be the place to ask this question but I'm starting here.

I'm using an "all Lua" Neovim configuration including Flutter-tools, Telescope and Bufferline.

I open a Flutter project, open the main.dart file, start the emulator and it doesn't matter if I use :FlutterRun or use Telescope to run the application. main.dart is in one buffer, __FLUTTER_DEV_LOG__ opens in a second buffer BUT it also opens another tab with the same buffers.

Now I have two tabs with a total of four buffers: 2 main.dart buffers and 2 __FLUTTER_DEV_LOG__ buffers.

Have you seen this or do you have any suggestions of where to look to prevent this from happening?

**Comment by dastagg** [comment]
I'm just going to close this question. 
I'm having other issues with Neovim and Flutter and it is challenging to both learn a new language and an editor configuration at the same time.
I'll use Android Studio for the time being and maybe come back to this in the future.

**Comment by akinsho** [comment]
@dastagg that's very fair re. using what works, so you can be productive. Re. the buffers and tabs situation, by default the dev log is opened in a *vertical split* however you can change this to open in a tab. It sounds like you had it open in a tab buffers are not duplicated in a tab but are actually the same buffers, so there weren't 4 buffers just 2 buffers visible in two tabs.

Either way, I'd have suggested you remove any custom changes you've made to the `open_cmd` for the `dev_log` presumable you copied it from the README block, but that block is explicitly not intended to be copied and is just for example sake.

**Comment by dastagg** [comment]
Thank you for your reply.

Yes, that is true, I did copy that block as I was trying to incorporate flutter_tools into a configuration created using chris@machine's "Neovim from Scratch" series.

In that configuration, there is an emphasis for using lsp-installer and a handler which sets up the keyboard commands and other things. I am trying to use that handler with flutter-tools without installing the Dart LSP.

I will take a look at that section in the block and see if I can determine how to fix it.

Thanks again.

**Comment by dastagg** [comment]
Just as a follow-up: Changed dev_log open_cmd = "edit" and that opens the dev log in it's own buffer.
Now it looks and acts the way I want it to.

I'll keep pushing at it until I get it together. Learn a little here... Learn a little there... The process continues...

Thanks for your help and THANKS for making this plugin!
