### ISSUE TITLE
Plugin recs out of date

### ISSUE THREAD

**Issue by mjlbach** [akinsho/flutter-tools.nvim#141]
> Read the lsp documentation this can be found in :h lsp or a short summary can be found [here](https://github.com/neovim/nvim-lspconfig#lsp-overview).
Autocompletion: Install an autocompletion plugin such as [nvim-compe](https://github.com/hrsh7th/nvim-compe).
Code actions/Rename UI:
For code actions, rename and other UI improvements, install an LSP UI plugin such as [lspsaga](https://github.com/glepnir/lspsaga.nvim)
For code actions only: [lsp-fastaction.nvim](https://github.com/windwp/lsp-fastaction.nvim)

I'd recommend removing lspsaga, and replacing it with [dressing.nvim](https://github.com/stevearc/dressing.nvim/issues), and removing cmpe in favor of nvim-cmp, up to you. I'm not sure that code actions/rename UI need to be explicitly mentioned because the default experience is IMO good enough.

**Comment by akinsho** [comment]
Thanks for pointing this out @mjlbach. I've removed all mention of other lsp plugins, I was never very keen on adding those links anyway, but was seeing a few issues where people were confused about how different things fit together and were expecting that functionality to be set up here.

**Comment by akinsho** [comment]
fixed by 0718bbf8c0fe370eaf3dc779ad87f714082be8e9
