### ISSUE TITLE
Discussion - Logs: highlight, filter, jump to source

### ISSUE THREAD

**Issue by amitkot** [akinsho/flutter-tools.nvim#142]
This is meant more as a discussion but discussions are not currently enabled for this project.

I'm a longterm Vim user and I want to move from VSCode to NeoVim for Flutter development.
I'm missing a bunch of features that people probably have good solutions for.

- What do you use for highlighting the log based on log levels?
- Is there a good way to filter the log displayed only for specific things?  (just flutter without the platform, regex based, etc.)
- How do you jump to source when building the app fails? gf, [C-W][C-F] or something better?

Thanks!

**Comment by amitkot** [comment]
Thanks @akinsho for replying and for developing this!
I would love to help with it and hope I can in the future, my current focus is determining if NeoVim + flutter-tools is a viable alternative for me for VSCode / IntelliJ.
I'll go over your pointers and check them, thanks!

btw, would you prefer we use the issues platform or GitHub's discussions feature?

**Comment by akinsho** [comment]
@amitkot I'm fine to enable the GitHub discussions feature but don't really have time or bandwidth to moderate conversations or to jump in really. If users using it are happy to self organize, then 🤷🏾‍♂️. What I'd rather avoid is a potential avenue for more work for myself, which I really can't deal with currently.

**Comment by akinsho** [comment]
Closing this out in a general tidy up, don't think there are any specific action points
