### ISSUE TITLE
Feature request: change status line color when running

### ISSUE THREAD

**Issue by amitkot** [akinsho/flutter-tools.nvim#145]
This is a nice feature of VSCode - when the project is being run the status line (airline, lualine, etc.) changes to a different color.

**Comment by akinsho** [comment]
@amitkot  I think the average nvim user would find changing their statusline invasive or contentious. Personally I think the right vim approach is to expose a component which a user can add to their statusline which there is already you can always just add your own autocmd when this plugin loads to change your status lines colour
