### ISSUE TITLE
Segfault when autocompletion is on

### ISSUE THREAD

**Issue by markstory** [akinsho/flutter-tools.nvim#148]
:wave: First, Thank you for putting this plugin together it is great to have IDE style tools available for flutter in neovim. I don't have a reproducible bug so I've not opened a proper bug report and understand that this may be too big of an ask. If that's the case feel free to close without responding :smile:

My situation is that I frequently get segmentation faults whilst editing a flutter project. It generally happens during typing in insertion mode. Because of that, I think it my problem is autocomplete related.

Other information on my setup:

* Neovim 0.7.0 (AppImage)
* My [vim configuration](https://github.com/markstory/vim-files/blob/master/vimrc)

Have you heard of anyone coming across something like this or encountered it yourself during the plugin development? Any suggestion on what I should look into next?

**Comment by akinsho** [comment]
Hi @markstory I don't really get segfaults during my development although tbh I no longer write flutter in my day job only my spare time 🤷🏿‍♂️. In either case if you're getting segfaults I think it's worth 1) trying to narrow them down 2) once you have something reproducible reporting it to the neovim dev team. Essentially neovim shouldn't segfault no matter what the plugin is doing or the user (within reason) but just saying it happens in an issue to the team won't be the most helpful, so I think once you can, I identify a pattern you should raise it there.

**Comment by br1anchen** [comment]
Just for your information, after some testing, I believe the plugin caused this is [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter). Once I uninstall `dart` language support for it, it does not crash.

**Comment by markstory** [comment]
@br1anchen That is interesting, I'm also using the dart treesitter language support. I'll try uninstalling that.

**Comment by markstory** [comment]
@br1anchen I uninstalled the treesitter dart module and switched to using a different vim plugin for syntax highlighting and haven't had any segfaults since. Thanks so much for the tip :heart:

**Comment by akinsho** [comment]
@markstory @br1anchen so the treesitter highlights shouldn't be causing segfaults, if it is then that might indicate a bug in nvim core or nvim-treesitter. I actually contributed to both the treesitter parser and added the highlights for nvim-treesitter so if something is breaking it would be good if either of you could report the issue to nvim-treesitter so that people can look at it and potentially fix the issue. I would be good to get a specific example that causes a crash, since I don't experience these myself.

**Comment by br1anchen** [comment]
@akinsho It was already reported in this [issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/2961)
