### ISSUE TITLE
[Bug]: flutter-tools not working

### ISSUE THREAD

**Issue by Jetandarkumar** [akinsho/flutter-tools.nvim#152]
**Describe the bug**
<-- Please ensure that you have read the README.md -->
yes

<-- Also report bugs using a minimal init.vim or **init.lua** rather than your full configuration -->
init.lua
`require("flutter-tools").setup{}
`

<-- Do Not Delete this template or will close the issue as it helps me debug reports -->
flutter-tools is not working at all like the **:FlutterCommands** are not working and not added in the :commands also.

**To Reproduce**

1. Go to '...' **init.lua** 
2. do '....'
3. `require("flutter-tools").setup{} `

**Expected behavior**
Flutter Commands should work.

**Screenshots**

**System information**

- OS:Ubuntu 20.04
- Flutter version: 3.0.1 and dart version : 2.17.1
- Is flutter in $PATH: yes because the flutter commands like flutter doctor are running in terminal
- neovim version:0.7.0

**Additional context**

**Comment by akinsho** [comment]
@Jetandarkumar this issue provides almost no additional information, I can't tell what I should be testing or what your setup is or anything like that. When I run flutter tools locally it works perfectly fine 🤷🏿‍♂️ . This issue also does not contain a *proper init.lua* that is what you are using just a single line to a function that already works on my side. *Please* provide enough information for someone else to understand how you have set up this plugin what does your minimal config look like?

**Comment by Jetandarkumar** [comment]
This is my **init.lua** I don't know if anyother thing matters here.

```
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
--require "user.comment"
require "user.nvim-tree"
-- require "user.fluttertools"

require("flutter-tools").setup{}
```

![Screenshot from 2022-06-08 19-12-41](https://user-images.githubusercontent.com/73706161/172700001-48835296-db53-4740-92de-8662738f6139.png)

If the plugin is working OK for you then of course the problem is from my end so closing this is  issue
