### ISSUE TITLE
[Bug]: Empty Console

### ISSUE THREAD

**Issue by EpsilonKu** [akinsho/flutter-tools.nvim#155]
**Describe the bug**
I can not use nvim-dap-ui console feature. More on https://github.com/rcarriga/nvim-dap-ui/issues/110
```
				require("flutter-tools").setup {
					debugger = {
						enabled = true,
						run_via_dap = true,
						register_configurations = function(_)
							-- require("dap").configurations.dart = {}
							-- require("dap.ext.vscode").load_launchjs()
						end,
					},
				}

```
**To Reproduce**

1. Start debugging
2. Toggle dap-ui
3. See console on buffer not on bottom

**Expected behavior**
Console on bottom.

**System information**

- OS: Arch Linux
- neovim version: NVIM v0.8.0-dev+441-ge651ae5864
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by EpsilonKu** [comment]
Ahh, yeah. I'm stupid. Flutter-tools show on repls. But I can't disable dev_log. 
```
				require("flutter-tools").setup {
					debugger = {
						enabled = true,
						run_via_dap = true,
					},
					dev_log = {
						enabled = false,
					},
				}
```
It seems `enable=false` doesn't work.

**Comment by akinsho** [comment]
@EpsilonKu this should definitely work as I use it, please check carefully that the config is correct and things have updated correctly on your side with your plugin manager

**Comment by EpsilonKu** [comment]
@akinsho I double checked. It works when `run_via_dap = false`, if it `true` it ignore both `enabled` and `open_cmd`.

**Comment by akinsho** [comment]
I've retested this locally and am definitely able to disable the dev log. I don't know why the OP can't but this functionality does work on the latest commit of this plugin
