### ISSUE TITLE
Feature request: Wrap Widgets

### ISSUE THREAD

**Issue by euler007** [akinsho/flutter-tools.nvim#165]
Would it be possible to add a wrapping functionality? Where in if a widget is added prior to the current widget it automatically formats it as a child with closing parentheses with ,'s and ;'s?

Also, great job you guys!! Loving the way its working currently. I am relatively new to neovim and flutter.

**Comment by rlch** [comment]
How would this functionally be different to the `Wrap with widget...` code-action? 

I don't think its worth implementing such a feature unless the plugin can provide a tangible benefit over the existing LSP implementation.

**Comment by euler007** [comment]
Honestly I was not aware about the wrap with widget feature, thanks for the quick response I will look into it

**Comment by euler007** [comment]
Hi, I got the wrap widget working by disabling my native lsp, thanks for that! But have come across another issue in the process and hoping someone could help out. Generally when lsp is enabled the debugger catches errors and when I hover/gl on the line it tells me the error but now while I can see it catching errors with markings next to line numbers I can not hover/gl to see what it is. For example in line 21 it catches the missing semicolon but there is no way I can see it


<img width="494" alt="Screenshot 2022-07-20 at 1 29 11 PM" src="https://user-images.githubusercontent.com/20284507/179928979-a7a496ab-b4a2-4afc-ab95-5636c3844471.png">

**Comment by akinsho** [comment]
@euler007 this isn't really specific to this plugin and relates to how you have setup your neovim lsp. This is kind of something that you need to handle on a global level not specific to dart or flutter. Please read through `:help vim.diagnostic` and look at read me for `nvim-lspconfig` (please do not use it to setup dart though, just read through the docs to understand the lsp in neovim better)

**Comment by euler007** [comment]
Noted, thanks!
