### ISSUE TITLE
[Bug]:  Auto import

### ISSUE THREAD

**Issue by euler007** [akinsho/flutter-tools.nvim#166]
**Describe the bug**

When i move a widget to another file, the import does popup in the outline, I select one and it works perfectly fine.But then when I go back again to see which other imports are missing none show up. Also, firebase does not popup in the outline for import

 
<-- Please ensure that you have read the README.md -->
<-- Also report bugs using a minimal init.vim or init.lua rather than your full configuration -->
<-- Do Not Delete this template or will close the issue as it helps me debug reports -->

**To Reproduce**

1. Move a widget which contains several imports to another file 
2. Open outline and missing imports are found here, but when you click on one it will work however, when you popup in outline again the other ones will not appear

**Expected behavior**
1. See all missing imports after one has been executed 
2. Probably have a auto-import all feature?

**System information**

- OS:MacOs
- Flutter version: 3.0.5
- Is flutter in $PATH: Yes
- neovim version: v0.7.0

**Comment by akinsho** [comment]
@euler007 these things are actually handled by the language server that is developed by the flutter team, this plugin just surfaces the server functionality. I doesn't implement it.

>   See all missing imports after one has been executed
    Probably have a auto-import all feature?

These are not things that this plugin can do by itself. It might be best to raise this functionality on the repository for the language server which I don't have to hand currently.
