### ISSUE TITLE
Add this package to mason.nvim registry

### ISSUE THREAD

**Issue by ArbazIrshad** [akinsho/flutter-tools.nvim#176]
I am using AstroNvim which uses [mason.nvim](https://github.com/williamboman/mason.nvim) as a Lsp package manager.
Can this package be registered to the mason registry so that I can install it through mason?

**Comment by akinsho** [comment]
@ArbazIrshad I don't think that makes much sense. Mason is for installing packages, not plugins. This is a plugin, so should be installed with a plugin manager like packer. It doesn't ship any binaries or anything like that. I believe this is likely a misunderstanding.

**Comment by akinsho** [comment]
Closing this out since my comment should answer this question and I've heard nothing back

**Comment by bit-void** [comment]
@akinsho I can't install this in astrovim due to it not existing on mason.nvim.

**Comment by akinsho** [comment]
@bit-void as I mentioned before, this is a *neovim plugin*, not a binary or some other type of tool that mason.nvim would handle. mason.nvim does not install plugins like this. I think you as the OP did have misunderstood how this plugin works and how the neovim ecosystem generally works. Please raise an issue in astrovim's repository about any issues relating to using it with this plugin. As I mentioned, what you are describing doesn't really make sense.

**Comment by bit-void** [comment]
@akinsho You're probably right, just struggling. For any future people that stumble on this, I found a convenient snippet on astrovim's wiki on how to configure this plugin: https://astronvim.github.io/Recipes/advanced_lsp
