### ISSUE TITLE
Terminal UI color numbers cause an error when plugin starts

### ISSUE THREAD

**Issue by anjerukare** [akinsho/flutter-tools.nvim#177]
When opening any dart file, the following error occurs:
```
Error detected while processing BufEnter Autocommands for "*.dart":
Error executing lua callback: ...tart/flutter-tools.nvim/lua/flutter-tools/utils/init.lua:75: '251' is not a valid color
stack traceback:
        [C]: in function 'nvim_set_hl'
        ...tart/flutter-tools.nvim/lua/flutter-tools/utils/init.lua:75: in function 'hl'
        ...tart/flutter-tools.nvim/lua/flutter-tools/utils/init.lua:77: in function 'highlight'
        ...er/start/flutter-tools.nvim/lua/flutter-tools/guides.lua:153: in function 'setup'
        ...ck/packer/start/flutter-tools.nvim/lua/flutter-tools.lua:78: in function <...ck/packer/start/flutter-tools.nvim/lua/flutter-tools.lua:73>
```
Before https://github.com/akinsho/flutter-tools.nvim/commit/789c41dddd602ae3d4d9e91f7c2f2461dc505e93 everything works fine.
Note that I am not using `termguicolors`.

**Comment by akinsho** [comment]
@anjerukare this should no longer error, but it won't work correctly for `cterm` colors. I personally do not use these and don't have the time to make them work. If you can only use termguicolors and want this to support cterm fully, please raise a PR, otherwise preventing an error is as far as I will go.

**Comment by anjerukare** [comment]
> @anjerukare this should no longer error

Yes, error doesn't occur.

> I personally do not use these and don't have the time to make them work.

It's fine. So far, I don't see any problems with the highlights with my config. The error message was the only problem for me.
