### ISSUE TITLE
Allow setting lineLength for formatting

### ISSUE THREAD

**Issue by kafendt** [akinsho/flutter-tools.nvim#178]
Hey there, thank you for the great work on this tool.
I was wondering whether it would be possible to add setting the line length for formatting.
I saw that the functionality was added to the dart analysis server here: https://github.com/dart-lang/sdk/issues/43043"
Unfortunately I wasn't able to find where this configuration is created within flutter-tools.nvim.

**Comment by akinsho** [comment]
@kafendt you can probably do this without any code changes, you just set
```lua
config = {
...
	lsp = {
		settings = {
			lineLength = 70
		}
	}
```
All the language server settings are just passed to the dartls so if your version supports it and neovim supports the behaviour of that setting it should just work, no issue on the repo required.

**Comment by rlch** [comment]
@kafendt Just confirming the above; this is my setup which I've been using for ~ a year now with no issues:

```dart
require('flutter-tools').setup {
  ...
  lsp = {
    ...
    settings = {
      lineLength = (function()
        return vim.fn.expand('%:p'):find '^/Users/rjm/Coding/Tutero/' and 100 or 80
      end)(),
      ...
    },
  },
}
```
This changes the line-length based off whether the project I'm working on is in a certain directory or not

**Comment by akinsho** [comment]
Thanks @rlch for the example,  gonna close this out @kafendt since it has a solution

**Comment by kafendt** [comment]
Perfect! Thanks a lot.
