### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by akinsho** [akinsho/flutter-tools.nvim#18]
![flutter-devices](https://user-images.githubusercontent.com/22454918/112320203-b5f31a80-8ca6-11eb-90b8-9ac934a842da.png)

**Comment by akinsho** [comment]
![image](https://user-images.githubusercontent.com/22454918/113897929-495a3e80-97c3-11eb-959f-9574319cd93c.png)

**Comment by rlch** [comment]
![fvm](https://user-images.githubusercontent.com/35163478/137667084-98c00c4b-ff8c-4d1e-869e-d2d51cf86f7e.png)
