### ISSUE TITLE
[Feature]  set project root in complex project structures.

### ISSUE THREAD

**Issue by dgriffith0** [akinsho/flutter-tools.nvim#180]
I have a Project Structure that looks like...

Root
 - Packages
   - Package1
   - Package2
   - Package3

My FlutteRun needs to execute from Package 2 (where my main.dart lives). If I am in package 3, it always wants to run from Package 3. Which makes it so I have to go back a directory if I am in package 1 or 3. Ex: FlutterRun -t ../package2/path/to/main.

Is there a way to specify where this should run from? Ideally I would want FlutterRun to execute from the project root so i can specify -t packages/package2/path/to/main and it works no matter where i am at. 

Thanks!

**Comment by JordanllHarper** [comment]
Would we want this in the setup_project({}) config? Or just as an argument to flutter run?

**Comment by sidlatau** [comment]
This should be possible with project config in `.nvim.lua`. With `cwd` you can control which package you want to run. You may even add several configurations for different packages and pick configuration on the `:FlutterRun`
```lua
require("flutter-tools").setup_project({
	{
		name = "Run example",
		target = "lib/main.dart",
		cwd = "example",
	},
})
```
