### ISSUE TITLE
Disable stop-on-exceptions.

### ISSUE THREAD

**Issue by wasabeef** [akinsho/flutter-tools.nvim#182]
I'd like to prevent the debugger from stopping on Exception?

Related articles.
- [Dart / Flutter - Debugger stops on caught exceptions](https://stackoverflow.com/questions/56802675/dart-flutter-debugger-stops-on-caught-exceptions)
- [Breaking on exceptions](https://docs.flutter.dev/development/tools/devtools/debugger#breaking-on-exceptions)
- [vm_services/setIsolatePauseMode](https://api.flutter.dev/flutter/vm_service/VmServiceInterface/setIsolatePauseMode.html)

![sfOpY](https://user-images.githubusercontent.com/1833474/189069634-97ff2113-af4a-4187-ae9b-c82fdad6a3a4.png)

**Comment by akinsho** [comment]
@wasabeef this is an issue for `nvim-dap` rather than this plugin since this plugin just relies on dap to handle the debugging. You can disable this in your `dap` config using
`require('dap').defaults.dart.exception_breakpoints = {}`

**Comment by wasabeef** [comment]
Thank you!
I think I've learned a lot.
