### ISSUE TITLE
How do I enable "just my code" feature?

### ISSUE THREAD

**Issue by FlafyDev** [akinsho/flutter-tools.nvim#184]
Whenever there is an exception I get redirected to a dart file that's unrelated to my project's files. Because of that, the LSP begins to analyze that dart file and every other dart file it depends on and that leads to performance issues and high cpu and memory usage.

I think this can be solved with the option "just my code" which forces the debugger to only show my code when an exception happens, but I can't find it anywhere.

**Comment by akinsho** [comment]
@FlafyDev you can disable stopping at exceptions, if you check the README for this option. If this is not what you have in mind please go through the documentation for nvim-dap as that is what is actually doing the debugging not this plugin
