### ISSUE TITLE
[Bug]: dartls not attaching to new buffer

### ISSUE THREAD

**Issue by jack-michaud** [akinsho/flutter-tools.nvim#185]
**Describe the bug**
When opening a new dart file in a flutter project, the new buffer is not aware of the language server. I cannot use things like hover, go to definition, and completion is not working. The original buffer still works. `FlutterLspRestart` does not fix the issue.

The error message I get looks like this:
```
method textDocument/hover is not supported by any of the servers registered for the current buffer
```

Minimal config:
```lua
  use {
    'akinsho/flutter-tools.nvim',
    requires = 'nvim-lua/plenary.nvim', 
    event = {"VimEnter"},
    config = function()
      local on_attach = function(client, bufnr)
        -- my binds, e.g.
        vim.keymap.set('n', '<space>h', vim.lsp.buf.hover, bufopts)
      end
      require("flutter-tools").setup{
        lsp = {
          on_attach = on_attach,
          color = {
            enabled = true,
            background = true,
            virtual_text = false,
          },
          settings = {
            showTodos = false,
            renameFilesWithClasses = "prompt",
            updateImportsOnRename = true,
            completeFunctionCalls = true,
            lineLength = 120,
          },
        },
        dev_log = { enabled = true },
      }
    end
  }
```

**To Reproduce**

1. Open a dart file
2. Open a second dart file in the same vim instance (via go to definition, or `:e lib/another_file.dart`
3. Attempt to hover

**Expected behavior**

**Screenshots**

`LspInfo` shows that the LSP is not attached to any new buffers.

![image](https://user-images.githubusercontent.com/13189762/191980096-d422f152-a884-41fb-a712-b36c46948656.png)
 

**System information**

- OS: Arch
- Flutter version: 3.3.2
- Is flutter in $PATH: Yup!
- neovim version: 0.7.2

**Additional context**

I use cmp and `null-ls`, if it matters.

**Comment by jack-michaud** [comment]
I am seeing you addressed something for this here https://github.com/akinsho/flutter-tools.nvim/commit/0bd239706f3a512b4619118a0f1e736976ff4f46.. I've ensured that I'm updated to the latest commit

**Comment by akinsho** [comment]
@jack-michaud I'm currently on nightly working on a flutter side project and don't see this issue. I haven't use stable in several months, so I don't know if it might relate to that, but I don't add changes to this plugin that often, so presumably it would have come up if it wasn't working for more people.

One thing I suggest is removing the lazy load on `VimEnter` that you've added. This plugin tries to lazy load itself, so a user lazy loading it on top of its own efforts will probably lead to weirdness

**Comment by jack-michaud** [comment]
Thanks for the rapid response @akinsho. I found that disabling Github copilot seemed to fix the issue, but I'll need to do more digging as to why. Up to you if you want to keep this issue open or close it since the fault may lie with copilot... other language servers do work. If I have more detail I'll update this thread.
