### ISSUE TITLE
__FLUTTER_DEV_LOG__ "tail -f" mode

### ISSUE THREAD

**Issue by amitkot** [akinsho/flutter-tools.nvim#186]
I noticed sometimes the `__FLUTTER_DEV_LOG__` buffer does not follow the latest debug lines in a "tail -f" manner, and sometimes it does.

This is something that could be useful to toggle for me. 
Probably - if not scrolled to the bottom - do not follow latest debug lines. If scrolled to the bottom - always show latest lines in "tail -f" mode.

It can also be a toggle switch I can map to some key if the above design is too complicated :)

If other people think this could be useful I might be inclined to do the actual coding.

**Comment by akinsho** [comment]
@amitkot I exclusively use this plugin with DAP nowadays so I'm not really very bothered by how it works in non-dap mode. Feel free to explore this as an option in the config that causes it to behave in the way you describe. I would suggest the simplest solution other than trying to do anything too fancy. Not sure if other users will chime in but if you raise a PR tag me and I'll have a look

**Comment by amitkot** [comment]
@akinsho I'll try DAP as well first, thanks!

**Comment by amitkot** [comment]
@akinsho I noticed that entering edit mode in the REPL window in DAP achieves what I was aiming for. 
Is there a way to have the REPL window follow last log line without being in edit mode in it?

**Comment by akinsho** [comment]
@amitkot dap's functionality is not under the control of this plugin, you can configure it using the docs from that repo or can ask the author of that plugin for the desired functionality, but generally this plugin defers to dap when it comes to handling of these sorts of things

**Comment by amitkot** [comment]
Thanks again @akinsho for the work you put into this plugin!
Closing this issue.
