### ISSUE TITLE
How can I set the dev log split to be modifiable ?

### ISSUE THREAD

**Issue by rohitsrao** [akinsho/flutter-tools.nvim#189]
Hi, 

I have configured flutter tools to have the dev log open up in a horizontal split. 

Is there some way I can set the split to be permanently modifiable ?! 

Currently I can bring my cursor into the dev log split and run the command ``set ma`` but this goes away when do a hot reload or a restart. 

Here is the link to my nvim [config](https://github.com/rohitsrao/nvim/blob/main/lua/user/fluttertools.lua).

Could someone please help me out with this ?!

**Comment by akinsho** [comment]
@rohitsrao You shouldn't be modifying the dev log. That's not really how it's intended to be used and even if it doesn't cause any breakage now it might do in the future. I would suggest not doing that

**Comment by akinsho** [comment]
tbh you are best off adding a mapping or something to your config to allow you to do this. The plugin isn't built to facilitate this, so there isn't an easier way to do it than that

**Comment by rohitsrao** [comment]
Alright. Thanks.
