### ISSUE TITLE
notification_style

### ISSUE THREAD

**Issue by MitaiDart** [akinsho/flutter-tools.nvim#193]
`notification_style = 'nvim-notify'` 
I prescribed it in the configuration, but nothing has changed, is there anything else needed?

**Comment by MitaiDart** [comment]
how can I configure auto-formatting when saving?

**Comment by akinsho** [comment]
Configuring autoformatting is an nvim lsp issue and is covered by lots of blog posts and the official help docs please check those resources. As for the notification style it's a beta option and is set by default `nvim-notify` is not a valid option for that

**Comment by MitaiDart** [comment]
the formatting issue was resolved as follows
```
local map = vim.api.nvim_set_keymap
local default_opts = {noremap = true, silent = true}
map('n', 'bf', '<cmd>lua vim.lsp.buf.format()<CR>', default_opts)
```

**Comment by MitaiDart** [comment]
now I don't know how to do folding with ufo, via lsp after all, it is not installed, because why are the settings made by flutter-tools, I'm confused...

**Comment by MitaiDart** [comment]
thanks for your plugin, it's cool

**Comment by MitaiDart** [comment]
would it be difficult for you to write an article about dap/dap-ui for Dart/Flutter
I tried to copy chunks from your config, but it turned out to be to no avail

**Comment by akinsho** [comment]
@MitaiDart I definitely don't have the time for that, but anyone else who wants to should please feel free.
