### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by leoncruz** [akinsho/flutter-tools.nvim#197]
I didn't find any setting to disable notifications in the project's documentation. Is there something for that? I'm currently using [nvim-notify](https://github.com/rcarriga/nvim-notify) and, sometimes, multiple notifications are shown at the same time, which ends up disturbing the view of the code

**Comment by gcanoxl** [comment]
Same happens!

**Comment by akinsho** [comment]
@leoncruz would be good to clarify which notifications need configurability. I'm not up for trying to make every single one configurable but I'm guessing you probably mean the ones that show whilst editing code. Rather than trying to silence notifications that tell you if something failed to open or failed to run since those are kind of critical to day to day usage

**Comment by leoncruz** [comment]
> I'm guessing you probably mean the ones that show whilst editing code

Yes.

> Rather than trying to silence notifications that tell you if something failed to open or failed to run since those are kind of critical to day to day usage

I think would be a user's option. If he likes to silence all notifications or leave someone, is his choice. 
I've been thinking about an option where it's possible leave all notifications, block all, or leave some with log level chosen. Example:

```lua
notifications = {
  enable = true,
  mode = "minimal", -- or all
  level = "ERROR"
}
```
that way the user would only see notifications with the log level ERROR. Or any other suggestions? I would like to know

**Comment by akinsho** [comment]
So I'm going to aim for something more simple than doing a bunch of granular checks to determine if notifications should be sent or not. A bunch of logic like this makes the code more complex and difficult to maintain.

I've just looked through the code base and almost all notifications are something a user must respond to or should be aware of. The main ones that could cause issue are the ones where I notify a user of some output from the language server that I don't know what it will be beforehand. These can and do get spammy.

The main focus for me in this issue will be finding a way to a) make them more manageable e.g. they should replace each other where possible e.g. the notification builds up to a point not 10 notifications b) allow these to be silenced all together.

We'll see how much of an issue remains when the language server notifications are reduced.

**Comment by textzenith** [comment]
If I can weight in here, @akinsho is right — better to set up a filter for them yourself. Then, you can be completely in control — and not only when working with Flutter, but in all your projects!

I use Noice to filter command line messages, and I follow the following advice to see only the immediately relevant diagnostic message:

https://www.reddit.com/r/neovim/comments/xqsboa/lsp_how_can_i_only_show_diagnostic_text_on_the/
