### ISSUE TITLE
'dartls -32007 file is not being analyzed' error whenever I open a file in Astronvim

### ISSUE THREAD

**Issue by ArbazIrshad** [akinsho/flutter-tools.nvim#199]
I am using Astronvim and I have setup flutter-tools plugin by following the guide [here](https://astronvim.github.io/Recipes/advanced_lsp#dart-flutter-flutter-toolsnvim).

Whenever I open a dart file I get the following error: `dartls -32007 file is not being analyzed`

Autocompletion and Fluttter commands works, but some feature like color highlights and goto definitions stops working in a dart file sometimes.

My config look like this: 

```
return {
  lsp = {
    skip_setup = { "dartls" }, -- skip lsp setup because flutter-tools will do it itself
    ["server-settings"] = {
      dartls = {
        -- any changes you want to make to the LSP setup, for example
        color = {
          enabled = true,
        },
        settings = {
          showTodos = true,
          completeFunctionCalls = true,
        },
      },
    },
  },
  plugins = {
    init = {
      {
        "akinsho/flutter-tools.nvim",
        requires = "nvim-lua/plenary.nvim",
        after = "mason-lspconfig.nvim", -- make sure to load after mason-lspconfig
        config = function()
          require("flutter-tools").setup {
            lsp = astronvim.lsp.server_settings "dartls", -- get the server settings and built in capabilities/on_attach
          }
        end,
      },
    },
  },
}
```

**Comment by ll931217** [comment]
The website example has been updated, see if the updated version works as it is working for me

**Comment by ArbazIrshad** [comment]
Unfortunately, The new docs still don't fix the problem for me.

**Comment by akinsho** [comment]
I haven't seen this issue in several months I believe and think it might have been an issue with dart LS in either case I don't think this is something the root cause of which is within this plugin. If anyone still experiences and has evidence that it relates to something this plugin is doing please comment here
