### ISSUE TITLE
[Feature request] `flutter pub add` command

### ISSUE THREAD

**Issue by 2n-1** [akinsho/flutter-tools.nvim#200]
Thank you so much for such a great package!

I was wondering if you thought about adding a `flutter pub add` command that accepts the package name as an argument.

I think that would be a great addition.

**Comment by akinsho** [comment]
@2n-1 I generally am not really looking to add pub commands to this plugin, as the commands I have added are primarily about making the actual development workflow easier in neovim, like restarting an emulator or automatically using an emulator or opening a list to choose from i.e. where I can provide added value. I definitely do not have the time or energy to re-implement all the various flutter commands as builtins for this plugin.

I'd look over a PR if you wanted to contribute some version of this that you imagine would be more useful than just typing `flutter pub add` in your terminal, but if the main value of this is having a custom UI in neovim, but it doesn't really provide much added value than typing in your commandline I'm not sure if this will be useful
