### ISSUE TITLE
[New Feature]:  flutter pub run build_runner watch

### ISSUE THREAD

**Issue by joseildofilho** [akinsho/flutter-tools.nvim#201]
would be nice some way to keep build_runner watch in background, so that it can improve a little bit the coding experience. Anyone could give me a hint where to start to implement it ?

**Comment by sidlatau** [comment]
I am using `ToggleTerm` for this: `TermExec cmd='fvm flutter pub run build_runner watch'`, so this functionality is just one keybinding away.

https://github.com/sidlatau/dotfiles/blob/51f6d1a5eef6c86c5751cbcbad9be4226a3ef331/nvim/.config/nvim/lua/user/whichkey.lua#L160-L163
