### ISSUE TITLE
Cannot Visualize Colors

### ISSUE THREAD

**Issue by AminBhst** [akinsho/flutter-tools.nvim#203]
I have flutter-tools setup but the color visualizer does not work. It only shows the color white no matter what the selected color is. 
Here is my config below : 
```lua 
 require("flutter-tools").setup {
    debugger = {
      enabled = true,
      run_via_dap = true,
    },
    outline = { auto_open = false },
    decorations = {
      statusline = { device = true, app_version = true },
    },
    widget_guides = { enabled = true, debug = true },
    dev_log = { enabled = false, open_cmd = "tabedit" },
    lsp = {
      color = {
        enabled = true,
        background = true,
        virtual_text = true,
        virtual_text_str = "■",
      },
      settings = {
        showTodos = true,
        renameFilesWithClasses = "prompt",
      },
      on_attach = require("ryewell.lsp.handlers").on_attach,
      capabilities = require("ryewell.lsp.handlers").capabilities,
    },
  }
```

**Comment by Chaitanyabsprip** [comment]
I am facing the same issue

**Comment by sidlatau** [comment]
It works for me:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/4973296/216058491-354acabf-19ad-43cc-b9f8-eed311872bd2.png">
My setup:
```lua
    color = { 
      enabled = true,
      background = false, 
      foreground = false, 
      virtual_text = true, 
      virtual_text_str = "■", 
    },
```
It works in both 3.3.10 and  3.7.0 Flutter versions.
What flutter versions you are using? What Neovim version?

**Comment by sidlatau** [comment]
Maybe transparent background is used?
I see it is not supported yet:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/4973296/216308443-15b18b66-08ff-4819-8aa1-c6a8396e7735.png">

There is a `config.background_color` property that could be set then.

https://github.com/akinsho/flutter-tools.nvim/blob/main/lua/flutter-tools/lsp/color/utils.lua#L203-L205

**Comment by Chaitanyabsprip** [comment]
oh alright, what is the format of the configuration property? I tried rrggbb with and without the # char and it is not working

**Comment by Chaitanyabsprip** [comment]
I followed the code to understand it, made it work. 

```lua
        color = {
          enabled = true,
          background = false,
          background_color = { r = 19, g = 17, b = 24},
          foreground = false,
          virtual_text = true,
          virtual_text_str = '■',
        },
```
The color I mentioned is basically the stock bg color of the color scheme I am using

**Comment by sidlatau** [comment]
Great! I created PR to update README with this missing background color config.
