### ISSUE TITLE
[Feature Request] Run tests and display results in outline view

### ISSUE THREAD

**Issue by baumths** [akinsho/flutter-tools.nvim#215]
It would be nice to have a shortcut to run all tests and see results in the outline view, something similar to flutter's vscode test tree.

**Comment by akinsho** [comment]
@baumths this functionality is achievable using:
* https://github.com/nvim-neotest/neotest
* https://github.com/sidlatau/neotest-dart
Rather than re-inventing the wheel/taking on the huge task of building a testing plugin these already do the job quite well an I recommend them

**Comment by baumths** [comment]
Thank you for introducing me to neotest, it is really a great solution.

And also, thank you for this amazing plugin, it makes life so much easier to develop dart/flutter apps, it's truly incredible. Great job!
