### ISSUE TITLE
[README.md/Installation] Single quotes must be used in vimL code

### ISSUE THREAD

**Issue by UnkwUsr** [akinsho/flutter-tools.nvim#22]
https://github.com/akinsho/flutter-tools.nvim#installation
```
Plug "neovim/nvim-lspconfig"
Plug "akinsho/flutter-tools.nvim"
```

**Comment by akinsho** [comment]
Course I haven't written much config in viml recently. Do you want to raise a PR for that @UnkwUsr?

**Comment by UnkwUsr** [comment]
I don't know what about next section, `packer.nvim`. Should we use single quotes or double quotes that :D?
UPD: also, for vim-plug we should set branch manually due to this repository use `main` instead of default for vim-plug `master`.
The result should look like this:
```
Plug 'akinsho/flutter-tools.nvim', { 'branch': 'main' }
```

**Comment by akinsho** [comment]
@UnkwUsr I used to use vim plug and I believe recent versions of that plugin don't require setting the branch to main it should just work so I don't think we should add the branch thing there. Regarding packer it doesn't have a quotation requirements so does not need to be changed only the vim plug bit and just the quotes

**Comment by UnkwUsr** [comment]
Fixed in https://github.com/akinsho/flutter-tools.nvim/commit/f263523d696e849a2712bb497e8a2cdd9618f29c

**Comment by MitaiGit** [comment]
Do you have a room in Gitter or Slack? where could I ask completely noob questions

**Comment by akinsho** [comment]
@MitaiGit nope no channel feel free to ask on here or raise a new issue, someone else might have similar questions or could be things I should add to the readme. If it's just general flutter dev stuff though there are probably better places for that

**Comment by MitaiGit** [comment]
> @MitaiGit нет канала, не стесняйтесь спрашивать здесь или поднимать новую проблему, у кого-то могут быть похожие вопросы или могут быть вещи, которые я должен добавить в readme. Если это просто общие разработки разработчиков флаттера, хотя, вероятно, для этого есть места получше

I'm embarrassed that my questions are of the "stupid" level", NVIM v0.5.0, OS Fedora, I can't configure it, the flutter commands, the display of errors in the code, or the auto-completion functions do not work, the notification appears just for a second, and disappears, here is my config
`"Основноые настройки редактора
syntax on "включает подсветку синтаксиса
set encoding=UTF-8
set autoindent "авто-отступ строки
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set textwidth=80 "длина строки
set number "показать номера строк

colorscheme trueboy

let g:airline_powerline_fonts = 1 "Включить поддержку Powerline шрифтов
let g:Powerline_symbols='unicode' "Поддержка unicode

"Плагины
call plug#begin()

" Nerdtree
Plug 'preservim/nerdtree'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'ryanoasis/vim-devicons'

Plug 'nvim-lua/plenary.nvim'
Plug 'akinsho/flutter-tools.nvim'
Plug 'dart-lang/dart-vim-plugin'

" Telescope
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'

call plug#end()

lua << EOF
require("flutter-tools").setup{}
EOF

lua << EOF
require("telescope").load_extension("flutter")
EOF`
![Снимок экрана от 2021-04-25 09-33-13](https://user-images.githubusercontent.com/32243762/115980858-5475e280-a5a9-11eb-8213-ff65d1c1174d.png)

**Comment by MitaiGit** [comment]
changed the path to the flutter, now there is no pop-up window with the error, and even some of the errors are shown, but not all, so for example, there is no absence ; at the end of the statement is not processed
what should I prescribe for displaying errors? and hints when you write code, for example, create a string object and then put it . the editor suggests all the functions available for strings
![Снимок экрана от 2021-04-25 10-00-50](https://user-images.githubusercontent.com/32243762/115981432-24c8d980-a5ad-11eb-87f3-e9500b3ee9ab.png)

**Comment by MitaiGit** [comment]
added this to init.vim, now errors are shown when changing the input mode, you can add a few comments on these items, what is responsible for what and what data can it accept?
`widget_guides = { 
    enabled =  false , 
  }, 
  closed_tags = { 
    highlight =  " ErrorMsg " , 
    prefix =  " > " 
  },
  dev_log ={ 
    Open_cmd =  " tabedit " , 
  }, 
  контур = { 
    open_cmd =  " 30vnew " , 
  }, `

**Comment by akinsho** [comment]
@MitaiGit regarding the errors those are handled by neovim's native lsp client. That can be configured using the documentation `:h lsp` and there are quite a few nice plugins e.g. `lspsaga` which can give nicer functionality and popup windows for errors so try some of those to improve how errors are presented.

Regarding the config I think those names are pretty clear not sure that comments would improve their clearness. Which bits are specifically unclear?

**Comment by MitaiGit** [comment]
https://github.com/neovim/nvim-lspconfig is the installation of this package required?

**Comment by akinsho** [comment]
Nope there is a note in the README explaining this, it is not required but if you use other language servers you will probably need it, just make sure *Not* to setup dartls with that plugin since this plugin already does it

**Comment by MitaiGit** [comment]
where is the error display redefined? now it only works when you change the mode

**Comment by akinsho** [comment]
@MitaiGit I don't fully understand the question. How errors are shown and handled is something that neovim's lsp handles not this plugin, so it isn't configurable via this plugin. You need to configure neovim's lsp to handle how errors are shown not this plugin.

Look at some plugins like https://github.com/glepnir/lspsaga.nvim and also some tutorials on setting up neovim lsp

**Comment by MitaiGit** [comment]
I am finally confused ((the output of the command gives the following
`{ {a print (vim.inspect(vim.lsp.buf_get_clients()))
    _cached_buffers = {
      [3] = { "import 'package:flutter/material.dart';", "", "void main(){",
 "  runApp();", "}", "", "class App extends statlessWidgets(){", "  String m
ystring = 'какая то строка'" }
    },
    _on_attach = <function 1>,
    cancel_request = <function 2>,
    config = {
      capabilities = {
        callHierarchy = {
          dynamicRegistration = false
        },
        textDocument = {
          codeAction = {
            codeActionLiteralSupport = {
              codeActionKind = {
                valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorE
xtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImpor
ts", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refacto
r.rewrite", "source", "source.organizeImports" }
              }
            },
            dynamicRegistration = false
          },
          completion = {
            completionItem = {
              commitCharactersSupport = false,
              deprecatedSupport = false,
              documentationFormat = { "markdown", "plaintext" },
              preselectSupport = false,
              snippetSupport = true
            },
            completionItemKind = {
              valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 }
            },
            contextSupport = false,
            dynamicRegistration = false
          },
          declaration = {
            linkSupport = true
          },
          definition = {
            linkSupport = true
          },
          documentHighlight = {
            dynamicRegistration = false
          },
          documentSymbol = {
            dynamicRegistration = false,
`
it is dart lsp config?

**Comment by MitaiGit** [comment]
Before your package, I had it done like this, and the code analyzer displayed errors instantly, how can I do the same but with your config?
`lua << EOF
require'lspconfig'.dartls.setup{
  cmd = { "dart", "/usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot", "--lsp" },
  on_attach=require'completion'.on_attach,
  filetypes = { "dart" },
}
EOF

lua << EOF
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
    underline = true,
    virtual_text = true,
    signs = true,
    update_in_insert = true,
  }
)
EOF`

**Comment by MitaiGit** [comment]
are you planning to make some video tutorials with explanations for noobs like me to promote the project?))

**Comment by akinsho** [comment]
@MitaiGit a big part of using this plugin assumes that the user understands how neovim's lsp works I'd rather not go down the rabbit hole of also explaining this functionality here as well. Unfortunately I think there is a bit of a language barrier so I don't fully understand what you are trying to achieve. You can still use
```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
vim.lsp.diagnostic.on_publish_diagnostics, {
	underline = true,
	virtual_text = true,
	signs = true,
	update_in_insert = true,
}
```lua
in your confg to control how all diagnostics work. This is a neovim level setting that this plugin doesn't change.

In terms of providing configuration for the rest of the lsp there is an `lsp` key in the configuration
so you can do 
```
lsp = {
  on_attach=require'completion'.on_attach,
}
```
or whatever other config you want to set.

This is also detailed in the `README`. I'm really not sure how else to help since I can't get a clear sense of what you need help with

**Comment by MitaiGit** [comment]
my knowledge of lua is 0, show me how it will be correct, please)
`lua << EOF
require("flutter-tools").setup{
  flutter_path = "/home/mitai/flutter/bin/flutter",
  widget_guides = {
    enabled = true,
  },
  closing_tags = {
    highlight = "ErrorMsg",
    prefix = ">"
  },
  dev_log = {
    open_cmd = "tabedit",
  },
  outline = {
    open_cmd = "30vnew",
  },
  lsp = {
    vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
      vim.lsp.diagnostic.on_publish_diagnostics, {
        underline = true,
        virtual_text = true,
        signs = true,
        update_in_insert = true,
      }
    )
    on_attach = require'completion'.on_attach,
    capabilities = my_custom_capabilities -- e.g. lsp_status capabilities
    settings = {
      showTodos = true,
      completeFunctionCalls = true -- NOTE: this is WIP and doesn't work currently
    }
  }
}
EOF

lua << EOF
require("telescope").load_extension("flutter")
EOF`

**Comment by akinsho** [comment]
```vim
lua << EOF
-- This diagnostic setup is Separate from this plugin and is a top level nvim lsp setting
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
vim.lsp.diagnostic.on_publish_diagnostics, {
	underline = true,
	virtual_text = true,
	signs = true,
	update_in_insert = true,
}

require("flutter-tools").setup{
	flutter_path = "/home/mitai/flutter/bin/flutter",
	widget_guides = {
		enabled = true,
	},
	closing_tags = {
		highlight = "ErrorMsg",
		prefix = ">"
	},
	dev_log = {
		open_cmd = "tabedit",
	},
	outline = {
		open_cmd = "30vnew",
	},
	lsp = {
		on_attach = require'completion'.on_attach,
	}
}

-- Only use this if you are using telescope if you do not use telescope do not use this
require("telescope").load_extension("flutter")
EOF
```

@MitaiGit this configuration should work. FWIW you need to have bit of an understanding of neovim's `lsp` and a little about `lua` just basic lua like correct syntax in order to be able to use these things more easily.

**Comment by MitaiGit** [comment]
now the output is empty, sorry I'm boring you probably already
:lua print (vim.inspect(vim.lsp.buf_get_clients()))
{}

**Comment by akinsho** [comment]
@MitaiGit what output is empty? So if you include the diagnostics handler config that stops you seeing error messages entirely or stops the client from being setup?

I have
```lua
 vim.lsp.handlers["textDocument/publishDiagnostics"] =
    vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics,
    {
      underline = true,
      virtual_text = false,
      signs = true,
      update_in_insert = false
    }
  )
```
in my config and this works, I'm not sure how the rest of your lsp settings are set up. Can you try the `LspInfo` command if you are also using `lspconfig` and print the output here.

**Comment by MitaiGit** [comment]
non lspconfig - E492: Это не команда редактора: LspInfo 
`call plug#begin()

" Nerdtree
Plug 'preservim/nerdtree'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'ryanoasis/vim-devicons'

Plug 'akinsho/flutter-tools.nvim'
Plug 'nvim-lua/completion-nvim'
Plug 'dart-lang/dart-vim-plugin'


" Telescope
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'

call plug#end()`
it seems mission impossible, I'm already ashamed to write to you for help, my skill level is too low

**Comment by akinsho** [comment]
@MitaiGit Ok lsp info doesn't exist because you are not using `lspconfig` which is fine, can you link your dotfiles repository link and I can have a look when I get a spare moment. I can't get enough of a sense of the problem from what you've posted here.

**Comment by MitaiGit** [comment]
what files do I need to attach to the repository?

**Comment by akinsho** [comment]
@MitaiGit glad you got something working, as you can probably see coc is a much older more established package so a lot of things work out of the box without tweaking. 

Tbh I was not able to get a clear picture of what wasn't working for you since I don't think I had enough clear information so wasn't able to help I'm sure it would have been solvable if I had the correct information, but as long as you can  do what you need then its all good.

**Comment by MitaiGit** [comment]
I stay with your package, what data and files should I provide for diagnostics?

**Comment by akinsho** [comment]
@MitaiGit do you keep your configuration in a public repo on github? if so if you link me that I will have a look. If not then just the minimal configuration files that cause this issue for you so your `init.vim` or `init.lua`. Basically the try to remove as much as possible that still causes this error then paste those files here.

**Comment by MitaiGit** [comment]
[init.vim.txt](https://github.com/akinsho/flutter-tools.nvim/files/6400485/init.vim.txt)

**Comment by akinsho** [comment]
One of the issues in the file you sent me is that you have a syntax error.
```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
vim.lsp.diagnostic.on_publish_diagnostics, {
    underline = true,
    virtual_text = true,
    signs = true,
    update_in_insert = true,
  }
)<-- you were missing the closing parens
```

**Comment by akinsho** [comment]
Also you really don't need to specify the path to flutter unless you have not put it in your `$PATH`, up to you anyway

**Comment by MitaiGit** [comment]
> One of the issues in the file you sent me is that you have a syntax error.
> 
> ```lua
> vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
> vim.lsp.diagnostic.on_publish_diagnostics, {
>     underline = true,
>     virtual_text = true,
>     signs = true,
>     update_in_insert = true,
>   }
> )<-- you were missing the closing parens
> ```

yes, the error has disappeared

**Comment by MitaiGit** [comment]
works))))) thank you for not abandoning an incompetent noob
can I ask you something else, is there no auto-completion yet? when you write imp and the editor suggests import ' '
and you also have multi-colored brackets on the screen(in the documentation). how do I do this?

**Comment by akinsho** [comment]
@MitaiGit you need to add in a plugin to provide completion this plugin doesn't provide that. The best one in my opinion is [nvim-compe](https://github.com/hrsh7th/nvim-compe). Regarding the multicoloured brackets there are a lot of plugins that do that e.g. [nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow) if you have treesitter setup or [rainbow](https://github.com/luochen1990/rainbow)

**Comment by MitaiGit** [comment]
Hi, what is the color scheme for the image in the documentation
It looks just amazing

**Comment by akinsho** [comment]
@MitaiGit I've changed colorscheme a few times in the last year so not sure exactly, in that screenshot it's probably `Th3Whit3Wolf/one-nvim`
