### ISSUE TITLE
Use on non-app Flutter code

### ISSUE THREAD

**Issue by justinmc** [akinsho/flutter-tools.nvim#222]
It seems like flutter-tools does not enable itself when I try to use it to work on the Flutter framework.  I assume it's using a heuristic to decide to run only when it detects some typical Flutter app files or structure.  However, I'd like to use it within the Flutter framework code, even if it's not possible to run it etc.

### Steps to reproduce

  1. `cd` into your Flutter framework repo code.  I usually work out of `packages/flutter`, but the root directory works, too.
  2. Open any dart file, maybe a common widget like: `packages/flutter/lib/src/material/text_field.dart`

Expected behavior: flutter-tools starts dartls and I see widget close brace labels, etc.
Actual behavior: flutter-tools and dartls do not start, and I can't use any of their features.

**Comment by akinsho** [comment]
Hi,

A while back some users were finding that they were getting too many diagnostic messages in framework files when they jumped to definition so I added a lot of them to the `analysisExcludedFiles`. You can reset this value to an empty list if you'd like diagnostics in those files assuming that's what's not working. This should be documented under the full configuration code block

**Comment by justinmc** [comment]
That worked for me, and indeed it is already in the README.  Thank you!
