### ISSUE TITLE
FlutterOutline show error

### ISSUE THREAD

**Issue by truongtd94** [akinsho/flutter-tools.nvim#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i use neovim, when i press 'a' key in outline, error appears, i tried many ways but still not working, please help me to fix this error. Thank!

### Expected Behavior

Image error:
https://github.com/truongtd94/errors/blob/master/2022222.png
https://github.com/truongtd94/errors/blob/master/1111.png

### Steps To Reproduce

1. Flutter outline
2. Press a key on widge outline panel
3. Display error

### Environment

```Markdown
- OS:
- Flutter version:
- Is flutter in $PATH:
- neovim version:
```

**Comment by akinsho** [comment]
This should now be fixed in the latest commit
