### ISSUE TITLE
[BUG] Running through dap on neovim 0.9 exits insert mode after every key stroke

### ISSUE THREAD

**Issue by D-James-GH** [akinsho/flutter-tools.nvim#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating to neovim 0.9 running a flutter app through the debugger causes insert mode to exit after every keystroke. Running through planary jobs does not have this issue. 

This is my config for flutter-tools:
```lua
require("flutter-tools").setup({
  ui = {
    border = "rounded",
    notification_style = "plugin",
  },
  decorations = {
    statusline = {
      app_version = false,
      device = false,
    },
  },
  debugger = {
    enabled = true,
    run_via_dap = true,
    register_configurations = function(paths)
      -- require("dap").configurations.dart = {}
      require("dap.ext.vscode").load_launchjs()
    end,
  },
  fvm = false,
  widget_guides = {
    enabled = false,
  },
  closing_tags = {
    highlight = "Comment",
    prefix = "// ",
    enabled = true,
  },
  dev_log = {
    enabled = true,
    open_cmd = "tabedit",
  },
  dev_tools = {
    autostart = true,
    auto_open_browser = true,
  },
  outline = {
    open_cmd = "30vnew",
    auto_open = false,
  },
  lsp = {
    color = {
      enabled = true,
      background = false,
      foreground = false,
      virtual_text = true,
      virtual_text_str = "■",
    },
    on_attach = function(client, bufnr)
      require("fg.lsp.setup").on_attach(client, bufnr)

      vim.api.nvim_create_autocmd("BufWritePre", {
        group = vim.api.nvim_create_augroup("FlutterTools", {}),
        buffer = bufnr,
        callback = function()
          vim.lsp.buf.format({ bufnr = bufnr })
        end,
      })
    end,
    capabilities = require("fg.lsp.setup").capabilities,
    settings = {
      showTodos = true,
      completeFunctionCalls = true,
      renameFilesWithClasses = "prompt",
      enableSnippets = true,
      analysisExcludedFolders = {
        ".dart_tool",
      },
    },
  },
})
```
I am not sure where to start with addressing this issue. I appreciate that this may not be an issue with flutter-tools directly and may be an issue with dap or my wider config. Any guidance on what might be the issue would be help full. 

### Expected Behavior

Should be able to type in insert mode without exiting to normal mode.

### Steps To Reproduce

1. run flutter app through dap

### Environment

```Markdown
- OS: Mac
- Flutter version: 3.7.9
- Is flutter in $PATH: yes
- neovim version: 0.9.0
```

**Comment by D-James-GH** [comment]
https://github.com/neovim/neovim/issues/22924 This could be the reason so may be fixed in 0.9.1.

**Comment by D-James-GH** [comment]
I have updated to neovim nightly and the problem seams to be fixed. Therefore do not believe there is any problem with this package. Closing this ticket.

**Comment by akinsho** [comment]
@D-James-GH thanks for raising it and linking to that issue, I'd noticed this problem but hadn't gotten round to investigating it properly yet.
