### ISSUE TITLE
lsp_derive_paths does not work anymore

### ISSUE THREAD

**Issue by nghialm269** [akinsho/flutter-tools.nvim#25]
Hi,
After commit https://github.com/akinsho/flutter-tools.nvim/commit/b9e707afa1d1ab1d035affb847c7efb3b13bc946, lsp_derive_paths feature does not work for me anymore.

The result of the `res` variable here https://github.com/akinsho/flutter-tools.nvim/blob/0f4294e90c3ecbbd5f259388159308c66a5be3ea/lua/flutter-tools/executable.lua#L44-L46
is `"/home/nghialm/.asdf/installs/flutter/2.0.4-stable/home/nghialm/.asdf/installs/flutter/2.0.4-stable"` (the result is duplicated)

I put some print statements to help debug:
```diff
diff --git a/lua/flutter-tools/job.lua b/lua/flutter-tools/job.lua
index 1fdb99a..50a558a 100644
--- a/lua/flutter-tools/job.lua
+++ b/lua/flutter-tools/job.lua
@@ -77,6 +78,8 @@ end
 ---stderr or stdout with only a single line
 function Job:__process_result(_, data, name)
   if data and type(data) == "table" then
+    print(vim.inspect(self))
+    print("JOB DATA: "..name.." data: "..vim.inspect(data))
     if data[#data] == "" then
       data[#data] = nil
     end
```

Here is the result:
```
{
  cmd = "asdf where flutter",
  id = 3,
  on_exit = <function 1>,
  on_stderr = <function 2>,
  <metatable> = <1>{
    __index = <table 1>,
    __is_alive = <function 3>,
    __make_args = <function 4>,
    __process_result = <function 5>,
    __set_status = <function 6>,
    close = <function 7>,
    new = <function 8>,
    result = { "" },
    send = <function 9>,
    start = <function 10>,
    status = 0,
    sync = <function 11>
  }
}
JOB DATA: stdout data: { "/home/nghialm/.asdf/installs/flutter/2.0.4-stable", "" }
{
  cmd = "asdf where flutter",
  id = 3,
  on_exit = <function 1>,
  on_stderr = <function 2>,
  <metatable> = <1>{
    __index = <table 1>,
    __is_alive = <function 3>,
    __make_args = <function 4>,
    __process_result = <function 5>,
    __set_status = <function 6>,
    close = <function 7>,
    new = <function 8>,
    result = { "/home/nghialm/.asdf/installs/flutter/2.0.4-stable" },
    send = <function 9>,
    start = <function 10>,
    status = 0,
    sync = <function 11>
  }
}
JOB DATA: stderr data: { "" }

{
  cmd = "asdf where flutter",
  id = 4,
  on_exit = <function 1>,
  on_stderr = <function 2>,
  <metatable> = <1>{
    __index = <table 1>,
    __is_alive = <function 3>,
    __make_args = <function 4>,
    __process_result = <function 5>,
    __set_status = <function 6>,
    close = <function 7>,
    new = <function 8>,
    result = { "/home/nghialm/.asdf/installs/flutter/2.0.4-stable" },
    send = <function 9>,
    start = <function 10>,
    status = 0,
    sync = <function 11>
  }
}
JOB DATA: stdout data: { "/home/nghialm/.asdf/installs/flutter/2.0.4-stable", "" }
{
  cmd = "asdf where flutter",
  id = 4,
  on_exit = <function 1>,
  on_stderr = <function 2>,
  <metatable> = <1>{
    __index = <table 1>,
    __is_alive = <function 3>,
    __make_args = <function 4>,
    __process_result = <function 5>,
    __set_status = <function 6>,
    close = <function 7>,
    new = <function 8>,
    result = { "/home/nghialm/.asdf/installs/flutter/2.0.4-stable/home/nghialm/.asdf/installs/flutter/2.0.4-stable" },
    send = <function 9>,
    start = <function 10>,
    status = 0,
    sync = <function 11>
  }
}
JOB DATA: stderr data: { "" }
```

It seems like the function is called twice, and although the two jobs have different job ids, the `result` table is shared between them.

**Comment by akinsho** [comment]
@nghialm269 thanks for raising the issue, it had been working fine on my end so I didn't realise. I refactored the startup since I was using `system` to make the call on startup and I realised it was causing about 80-100ms slowdown to vim's startup.

It's strange that you are seeing it duplicate the output or that it runs more than once. I use the `flutter sdk-path` command on linux which only runs once and gives the right output.

I'm not sure why the function would run twice in your case, the handler you logged is an on exit handler so that must mean two jobs were started but I'm not sure how that's possible or why the table would be being re-used the results table should be unique to each job since it's created from scratch when creating a job 🤔

**Comment by akinsho** [comment]
@nghialm269 I've been tinkering with this and I think the main issue is that it's pretty hard to manage terminal output from `stdout` using `nvim`'s `jobstart` it returns the output in chunks which have to be pieced back together. I'm considering adding `plenary` as a dependency since that already has a jobs modules that deals with all this messiness already

**Comment by nghialm269** [comment]
@akinsho I just tested with a minimal init.lua and lsp_derive_paths works fine, so maybe something is wrong with my configuration, I will check later when I have time.

**Comment by akinsho** [comment]
@nghialm269 has this changed this the most recent update? I'm now using plenary so their job implementation is more robust than my homegrown one was

**Comment by nghialm269** [comment]
@akinsho
I can reproduce the plugin gets loaded twice by using this minimal `init.lua`, seems like a bug of `packer.nvim`:
```lua
-- install packer
local fn = vim.fn

local install_path = '/tmp/nvim/site/pack/packer/start/packer.nvim'

vim.cmd [[set packpath=/tmp/nvim/site]]

local function load_plugins()
  local use = require('packer').use
  require("packer").startup(
    {
      function()
        use 'wbthomason/packer.nvim'
        use {
          'dart-lang/dart-vim-plugin',
          ft = {'dart'},
        }
        use {
          'akinsho/flutter-tools.nvim',
          requires = {
            'nvim-lua/plenary.nvim',
            'mfussenegger/nvim-dap',
          },
        }
      end,
      config = {package_root = '/tmp/nvim/site/pack'}
    }
  )
end

_G.load_config = function()
  vim.lsp.set_log_level("trace")
  require'flutter-tools'.setup{
    experimental = {
      lsp_derive_paths = true,
    },
    flutter_lookup_cmd = "asdf where flutter",
    widget_guides = {
      -- highlight = "NonText",
      enabled = true,
    },
    closing_tags = {
      highlight = "Comment",
      prefix = "-- "
    },
    dev_log = {
      open_cmd = "10new",
    },
    outline = {
      open_cmd = "35vnew",
    },
    lsp = {
      -- on_attach = on_attach,
      -- capabilities = capabilities,
      flags = {
        debounce_text_changes = 150
      },
      settings = {
        dart = {
          enableSdkFormatter = true,
          lineLength = 80,
          completeFunctionCalls = true,
          showTodos = true,
        }
      },
    },
    -- debugger = {
    --   enabled = true,
    -- }
  }
end

if fn.isdirectory(install_path) == 0 then
  fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
  load_plugins()
  require('packer').sync()
  vim.cmd 'autocmd User PackerComplete ++once lua load_config()'
else
  load_plugins()
  _G.load_config()
end
```

If I disable `dart-lang/dart-vim-plugin`, the plugin only loads once now.

After that, commit https://github.com/akinsho/flutter-tools.nvim/commit/464a9193d8639fffb2d65b418fb9bc2a314b1a90 works fine for me now, but the plenary version (https://github.com/akinsho/flutter-tools.nvim/commit/7c25866f90e202eb6011c237beb679f9e266d3ee) doesn't work for me:
![image](https://user-images.githubusercontent.com/13317164/115177119-b8576180-a0f8-11eb-9b0e-c2b2cf351cb9.png)

**Comment by akinsho** [comment]
@nghialm269 not sure why running `asdf` twice would be an issue at all tbh, but one thought I have is that your config should probably be part of a packer `config` key rather than a global that gets called separately. Try doing
```lua
use {"flutter-tools", config = function()
  require('flutter-tools').setup() <-- config here
end}
```

**Comment by nghialm269** [comment]
> @nghialm269 not sure why running `asdf` twice would be an issue at all tbh,
With pre-plenary version, for some reason running the job twice results in duplicate in the output as described in the original thread, but with plenary it is not an issue anymore.

> but one thought I have is that your config should probably be part of a packer `config` key rather than a global that gets called separately. Try doing
> 
> ```lua
> use {"flutter-tools", config = function()
>   require('flutter-tools').setup() <-- config here
> end}
> ```

The minimal configuration is from lspconfig repo, I also tried to put flutter setup in packer `config` key but the result is the same.

Anyway, I found the bug with plenary in #28 so it's all okay now.
