### ISSUE TITLE
Use private code of nvim lsp

### ISSUE THREAD

**Issue by Decodetalkers** [akinsho/flutter-tools.nvim#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/60290287/236634252-af81f3d8-b624-4619-a080-7fb33a67d7a8.png)
![image](https://user-images.githubusercontent.com/60290287/236634271-7739f4d7-c5ef-487d-9d83-bfc748ea1091.png)

As you have seen, seems the code is private.. 

### Expected Behavior

Maybe there is other way?

### Steps To Reproduce

see the document of lsp.lua, it is marked as @private
```lua
  -- Track this so that we can escalate automatically if we've already tried a
  -- graceful shutdown
  local graceful_shutdown_failed = false
  ---@private
  --- Stops a client, optionally with force.
  ---
  ---By default, it will just ask the - server to shutdown without force. If
  --- you request to stop a client which has previously been requested to
  --- shutdown, it will automatically escalate and force shutdown.
  ---
  ---@param force boolean|nil
```

### Environment

```Markdown
- OS:
- Flutter version:
- Is flutter in $PATH:
- neovim version:
```

**Comment by akinsho** [comment]
Just pushed a quick fix, thanks for pointing this out although feel free to raise a PR against this sort of thing in the future.

**Comment by Decodetalkers** [comment]
> 

you have missing another. >_<

**Comment by akinsho** [comment]
@Decodetalkers I don't see any warnings about using `client.request` also please raise a PR for these if you'd like. Generally speaking as the pace of development in neovim is quite fast lots of lsp stuff this plugin does/did has become outdated eventually fallen afoul of the new mechanisms. I don't chase after refactoring everything immediately since otherwise I'd get no actual work done. Thankfully there are hopefully deprecation cycles/ outside contributions to help

**Comment by Decodetalkers** [comment]
> @Decodetalkers I don't see any warnings about using `client.request` also please raise a PR for these if you'd like. Generally speaking as the pace of development in neovim is quite fast lots of lsp stuff this plugin does/did has become outdated eventually fallen afoul of the new mechanisms. I don't chase after refactoring everything immediately since otherwise I'd get no actual work done. Thankfully there are hopefully deprecation cycles/ outside contributions to help

I use neovim 0.9.0, and in lsp.lua, it is marked as

```lua
 ---@private
  --- Sends a request to the server.
  ---
  --- This is a thin wrapper around {client.rpc.request} with some additional
  --- checks for capabilities and handler availability.
  ---
  ---@param method string LSP method name.
  ---@param params table|nil LSP request params.
  ---@param handler lsp-handler|nil Response |lsp-handler| for this method.
  ---@param bufnr integer Buffer handle (0 for current).
  ---@return boolean status, integer|nil request_id {status} is a bool indicating
  ---whether the request was successful. If it is `false`, then it will
  ---always be `false` (the client has shutdown). If it was
  ---successful, then it will return {request_id} as the
  ---second result. You can use this with `client.cancel_request(request_id)`
  ---to cancel the-request.
  ---@see |vim.lsp.buf_request()|
  function client.request(method, params, handler, bufnr)
    if not handler then
      handler = assert(
        resolve_handler(method),
        string.format('not found: %q request handler for client %q.', method, client.name)
      )
    end
    -- Ensure pending didChange notifications are sent so that the server doesn't operate on a stale state
    changetracking.flush(client, bufnr)
    bufnr = resolve_bufnr(bufnr)
    local _ = log.debug()
      and log.debug(log_prefix, 'client.request', client_id, method, params, handler, bufnr)
    local success, request_id = rpc.request(method, params, function(err, result)
      handler(
        err,
        result,
        { method = method, client_id = client_id, bufnr = bufnr, params = params }
      )
    end, function(request_id)
      client.requests[request_id] = nil
      nvim_exec_autocmds('User', { pattern = 'LspRequest', modeline = false })
    end)

    if success and request_id then
      client.requests[request_id] = { type = 'pending', bufnr = bufnr, method = method }
      nvim_exec_autocmds('User', { pattern = 'LspRequest', modeline = false })
    end

    return success, request_id
  end
```

Emm. I don't know when it is marked as private..

**Comment by Decodetalkers** [comment]
ok, the developers of nvim are still using it..no worry..  at least this time

**Comment by akinsho** [comment]
It's also used by other lsp plugins

`nvim-jdtls` - https://github.com/search?q=repo:mfussenegger/nvim-jdtls%20client.request&type=code

`rust-tools` - https://github.com/search?q=repo:simrat39/rust-tools.nvim%20client.request&type=code

To be clear it isn't just as simple as it's private don't use it. Because a) things are changing very fast b) if there is no public mechanism for doing something then this can be a way to achieve it at least for that and previous versions of nvim etc.

i.e. this is a remove when simple and easy not a crusade especially when there might not be better options

**Comment by Decodetalkers** [comment]
> 

Thanks very much. I see
