### ISSUE TITLE
[BUG] FlutterOutline

### ISSUE THREAD

**Issue by marcosdanielr** [akinsho/flutter-tools.nvim#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 When I try use Code Action of Flutter Outline nothing happen.

### Expected Behavior

  I expected that code actions of Flutter Outline worked, like wrap, extract, etc. 

### Steps To Reproduce

Video reproducing the bug:

https://github.com/akinsho/flutter-tools.nvim/assets/91376596/60cbac9d-6864-449c-8b6b-4b9437d6624c

### Environment

```Markdown
- OS: ArchLinux
- Flutter version: 3.7.3
- Is flutter in $PATH: "$HOME/.asdf/installs/flutter/3.7.0-stable/bin":"$PATH"
- neovim version: 0.9.1
```

**Comment by akinsho** [comment]
@marcosdanielr please use code actions in the code directly and not in the outline window. I'm in the process of deprecating this feature as it's more trouble than it's worth for me

**Comment by marcosdanielr** [comment]
Ok. Thanks, bro!
