### ISSUE TITLE
[BUG]  nvim gets halt 

### ISSUE THREAD

**Issue by Pratham16112002** [akinsho/flutter-tools.nvim#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I press enter in insert Mode the neovim Gets halt for a second every time and then moves to second line and this is not happening with other lsp's just occur when I use this plugin 

### Expected Behavior

When I press enter in insert Mode the cursor should move to the next line immediately without halting 

### Steps To Reproduce

1. Linux 

### Environment

```Markdown
- OS:
- Flutter version:
- Is flutter in $PATH:
- neovim version:
```

**Comment by akinsho** [comment]
@Pratham16112002 this isn't reproducible for me as you've described. This issue also contains next to no information other than saying you use some linux distro e.g. flutter version, neovim version etc. as such this is pretty impossible to debug or help with so will close this out without valid info.
