### ISSUE TITLE
[BUG] Flutter Outline Wrap with Widget

### ISSUE THREAD

**Issue by julian-ch-02** [akinsho/flutter-tools.nvim#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i'm trying to wrap the widget using flutter outline, it not working as expected. Although i've been waited for more than a minute.

### Expected Behavior

It should wrap my widget when i hit enter

### My Config

require("flutter-tools").setup {
  decorations = {
    statusline = {
      app_version = true,
      device = true,
    }
  },
  fvm = true,
  widget_guides = {
    enabled = true,
  },
  outline = {
    open_cmd = "30vnew", -- command to use to open the outline buffer
    auto_open = false -- if true this will open the outline automatically when it is first populated
  },
  lsp = {
    color = {
      -- show the derived colours for dart variables
      enabled = true,         -- whether or not to highlight color variables at all, only supported on flutter >= 2.10
      background = true,      -- highlight the background
      foreground = false,     -- highlight the foreground
      virtual_text = true,    -- show the highlight using virtual text
      virtual_text_str = "■", -- the virtual text character to highlight
    },
    on_attach = function(client, bufnr)
      on_attach(client, bufnr)
      enable_format_on_save(client, bufnr)
    end,
    capabilities = capabilities, -- e.g. lsp_status capabilities
    settings = {
      enableSdkFormatter = true,
      completeFunctionCalls = true,
      enableSnippets = true,
    }
  }
}

### Environment

```Markdown
- OS: Windows 10
- Flutter version: 3.10.5
- using Fvm
- neovim version: 0.9.0
```

**Comment by akinsho** [comment]
@julian-ch-02 this feature is due to be deprecated please use normal code actions in your flutter code rather than depending on the outline 🙏🏾
