### ISSUE TITLE
[BUG] cannot format using the built-in lsp

### ISSUE THREAD

**Issue by akbng** [akinsho/flutter-tools.nvim#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running LSP format fails with the message: 
`lsp format request failed, no matching language servers.`
It was working previously. Suddenly it stopped formatting! without any changes made to the configs.
![image](https://github.com/akinsho/flutter-tools.nvim/assets/91788199/851c7140-3b1b-471a-aa54-f4ffb9c60d38)

### Expected Behavior

It should format the current document using the LSP format command.

### Steps To Reproduce

Using NvChad with the below config in the `custom/plugins.lua` that uses Lazy.nvim:
```lua
{
    "akinsho/flutter-tools.nvim",
    lazy = false,
    dependencies = {
      "nvim-lua/plenary.nvim",
      "stevearc/dressing.nvim", -- optional for vim.ui.select
      "neovim/nvim-lspconfig",
    },
    config = function()
      local on_attach = require("plugins.configs.lspconfig").on_attach
      local capabilities = require("plugins.configs.lspconfig").capabilities
      require("flutter-tools").setup {
        lsp = {
          on_attach = on_attach,
          capabilities = capabilities,
        },
      }
    end,
  }
```

### Environment

```Markdown
- OS: Windows 10 pro 22H2 19045.2965
- Flutter version: 3.10.6
- Dart version: 3.0.6
- Is flutter in $PATH: yes
- neovim version: 0.9.1
```

### Anything else?

Other functionalities like code actions are working fine.

![image](https://github.com/akinsho/flutter-tools.nvim/assets/91788199/eeb2321e-61f2-429d-9f53-17e0281078ed)

**Comment by mohamad-supangat** [comment]
check using :LspInfo is dart ls running 
![image](https://github.com/akinsho/flutter-tools.nvim/assets/48933993/4ae34c76-446b-4804-aa8d-16e633e9e9e9)

**Comment by akbng** [comment]
It was attached to the buffer, _I forgot to include it_. Also, how would the code actions, and LSP rename would have worked?
Anyway, I have configured the LSP server separately with lspconfig along with this plugin's default configuration. **It seems to work fine.** But that's just a workaround, I need to know why this was happening at all!
### Here's the `lspconfig.lua`:
```lua
lspconfig.dartls.setup {
  on_attach = on_attach,
  capabilities = capabilities,
  settings = {
    dart = {
      showTodos = true,
      completeFunctionCalls = true,
      renameFilesWithClasses = "prompt",
      enableSnippets = true,
      updateImportsOnRename = true,
      enableSdkFormatter = true
    }
  }
}
```
### Here's the Lazy plugin inside `plugins.lua`:
```lua
{
   "akinsho/flutter-tools.nvim",
    lazy = false,
    dependencies = {
      "nvim-lua/plenary.nvim",
      "stevearc/dressing.nvim", -- optional for vim.ui.select
    },
    config = true,
},
```
### Here's the output of the `:LspInfo`
![image](https://github.com/akinsho/flutter-tools.nvim/assets/91788199/06c30d89-1bcc-4659-b4fd-9ea64325b486)

**Comment by hyperion2144** [comment]
if you use `null_ls.nvim`, you can add   `null_ls.builtins.formatting.dart_format` into it's sources, and then can format code auto.

**Comment by akbng** [comment]
> if you use `null_ls.nvim`, you can add `null_ls.builtins.formatting.dart_format` into it's sources, and then can format code auto.

🙏Thank you, this resolves the issue completely. And I was also able to auto-format on save using null_ls
