### ISSUE TITLE
[BUG] flutter command not found in nvim

### ISSUE THREAD

**Issue by achrip** [akinsho/flutter-tools.nvim#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the plugins works exceptionally for the most part. The weird thing is that Neovim doesn't seem to recognize the commands from this plugin. But if I use the command `:Telescope flutter commands` it shows me the list of commands and all runs well. Any suggestions? 

neovim v.0.9.0

this is my .config/nvim file tree
![image](https://github.com/akinsho/flutter-tools.nvim/assets/88046815/8899dae4-0f64-4c1a-bf9e-be6695f766ec)

this is the flutter-tools.lua, but this file doesn't seem to do anything
![image](https://github.com/akinsho/flutter-tools.nvim/assets/88046815/d057c906-a0c4-4855-8636-95cdfaa359b7)

### Expected Behavior

I should be able to run the `:Flutter` command 

### Steps To Reproduce

1. with `Packer.nvim`, add the plugin for `flutter-tools.nvim`
2. `:so` then `:PackerSync`
3. see error when trying to run `:FlutterRun` and other flutter commands with exception E492: Not and editor command: FlutterRun

### Environment

```Markdown
- OS: Ubuntu LTS 22.04.3
- Flutter version: 3.10.6
- Is flutter in $PATH: yes (installed via snap)
- neovim version: 0.9.0
```

**Comment by akinsho** [comment]
@achrip the plugin only lazily loads itself inside of dart files. Can you confirm you've checked this inside of a dart file
