### ISSUE TITLE
[Discussion] How do i open __FLUTTER_DEV_LOG__

### ISSUE THREAD

**Issue by joeldegerman99** [akinsho/flutter-tools.nvim#281]
Hi,

I would like to know if there is a way to open the dev log if I accidentally closed it without restarting.

// Joel

**Comment by Thesmader** [comment]
@joeldegerman99 You can find the list of buffers by exeucting the `:buffers` command like below:

![image](https://github.com/akinsho/flutter-tools.nvim/assets/34758667/09a8c13b-4ac9-4ea5-8905-e182bec52999)

You can then use that information to reopen the buffer. Let's say you want to reopen the tab devlog buffer in a new tab, you can execute `tabnew | buffer 16` or `tabnew | buffer __FLUTTER_DEV_LOG__`

**Comment by FredrikMorstad** [comment]
Building on what @Thesmader answered I created a binding for opening the dev log. This can be useful until #121 is finished.
 
`vim.keymap.set({ "n" }, "fl", ":vnew | buffer __FLUTTER_DEV_LOG__<CR>", { remap = false, desc = "Open flutter dev log in vertical split" })`

**Comment by joeldegerman99** [comment]
I will close this, since it is not an issue per say. But thanks a lot guys, i am new to nvim and i am really grateful for the help
