### ISSUE TITLE
vim.lsp.buf.hover() moves my cursor to the popup window leading to unwanted behaviour

### ISSUE THREAD

**Issue by acicco** [akinsho/flutter-tools.nvim#29]
I would expect the cursor to stay in place

![image](https://user-images.githubusercontent.com/12491883/115254949-bf489900-a125-11eb-86d9-04618cb8bb8d.png)
****

**Comment by akinsho** [comment]
@acicco thanks for trying out the plugin.

It doesn't actually do anything relating to the hover window at all though. This behaviour is that of the native neovim lsp. I think there was a PR in neovim recently that meant you could tweak how the hover handler behaves. I can't remember what it was off the top of my head. I use `lspsaga.nvim` so not really up to date on how the native client does some things

**Comment by acicco** [comment]
That's really strange, because as soon as I comment out your plugin it does not happen. Do you have an idea of what it could be? or what sort of more information I could provide to you?

**Comment by akinsho** [comment]
Hmm 🤔 I just searched through the plugin for all the points where the cursor is moved and it's mainly in relation to the outline window. Can you try deactivating that handler using
```lua
lsp = {
    handlers = {
      ["dart/textDocument/publishOutline"] = function() end -- this is no-op
    },
}
```
That should stop that module from running I need to add an easier way to deactivate it later. Can you see if that makes a difference?

**Comment by acicco** [comment]
I have tried
```vim
lua << EOF
require("flutter-tools").setup{
    lsp = {
        handlers = {
          ["dart/textDocument/publishOutline"] = function() end -- this is no-op
        },
    }
}
EOF
```
But the behaviour still occurs, as soon as I load a file. I run it and as soon as the popup happens, it takes a second before it goes to it instead of staying where it was 🤔

**Comment by akinsho** [comment]
@acicco can you try this with a minimal init.lua e.g.
```
nvim -u <path/to/minimal.lua> --noplugin ./lib/<file-here>.dart
```

```lua
vim.cmd("packadd flutter-tools.nvim")

require("flutter-tools").setup{}
```
Then try `vim.lsp.buf.hover()`

I just tried it with no other plugins other than this one and I can't reproduce the issue you are having

**Comment by acicco** [comment]
It seems to be something with
```vim
    Plug 'neovim/nvim-lspconfig'
```
As soon as I disable that seems to be fine, however I still need to dig a bit further

**Comment by acicco** [comment]
I think I found another track, Running `:LspInfo` I seem to be having 2 dartls clients attached to the buffer, so when I run the hover command it gets executed twice hence why my cursor goes to the popup window. Is your plugin attaching the dartls server somewhere?

![image](https://user-images.githubusercontent.com/12491883/115532395-a6f38e00-a28d-11eb-8028-aab04a1b443a.png)

**Comment by acicco** [comment]
Sorry my bad, I just saw your note on the readme that dart should not be set on the lsp config as this plugin does it for you.
