### ISSUE TITLE
Adding snippet support 

### ISSUE THREAD

**Issue by jeevanpranav02** [akinsho/flutter-tools.nvim#293]
I have been using this plugin for quite long time and it is a great plugin for Flutter development. The only thing that is bothering me is that I have been searching for flutter snippets to work with nvim and I thought of using [awesome-flutter-snippets](https://github.com/Nash0x7E2/awesome-flutter-snippets) but I don't know how to make it work.

**Comment by akinsho** [comment]
@jeevanpranav02 snippets are actually out of scope for this plugin there are already a lot of great plugin to use snippets and plugins that provide snippets

**Comment by Thesmader** [comment]
@jeevanpranav02 you can use a snippet plugin to have your own snippets, or use community snippets like [awesome-flutter-snippets](https://github.com/Nash0x7E2/awesome-flutter-snippets) in neovim. There are a lot of snippet plugins available like: [Luasnip](https://github.com/L3MON4D3/LuaSnip), [Snipmate](https://github.com/garbas/vim-snipmate), [Ultisnips](https://github.com/SirVer/ultisnips), etc. 

Luasnip allows you to load VSCode style snippets really easily. Check the docs [here](https://github.com/L3MON4D3/LuaSnip#add-snippets). You can install awesome-flutter-snippets as a plugin (specifying it in your plugin manager configuration should do it), and let Luasnip load those snippets.

**Comment by jeevanpranav02** [comment]
@akinsho @Thesmader Thanks mate! I'll look into LuaSnip and I my friend suggested this plugin [vim-vsnip](https://github.com/hrsh7th/vim-vsnip). I try both and use which better suits me.
