### ISSUE TITLE
[BUG] Insane delay after pressing enter

### ISSUE THREAD

**Issue by throwaway-squared** [akinsho/flutter-tools.nvim#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ive seen only one guy describe the same issue

when i press enter to get a new line in insert mode, it takes a good few seconds before nvim catches up and actually draws to the screen, although my input is still read and i can still type whats supposed to be in the next line, it just takes a while to actually show it

this only happens when flutter-tools is running (ive only tested it on the lib/main.dart file)

### Expected Behavior

upon pressing enter, a new line should be created without a delay of drawing it to the screen

### Steps To Reproduce

1. have my configuration (idk if this happens with other configs)
2. open a dart file (mainly lib/main.dart in a flutter project)
3. type some code
4. press enter
   should be noted that it seems to appear more often when splitting brackets in this manner]
   (| is the cursor): 
   1. appBar: AppBar(|)
   2. press enter

### Environment

Markdown
- OS:
```
Artix Linux
6.5.5-artix1-1
```
- Flutter version:
```
Flutter 3.13.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ead455963c (11 days ago) • 2023-09-26 18:28:17 -0700
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0
```
- Is flutter in $PATH: yes definitely
- neovim: 
```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1694285958
```
nvim config: https://codeberg.org/qube/dot-squared/src/branch/main/.config/nvim
```


### Anything else?

_No response_

**Comment by gradunza5** [comment]
For whatever it's worth, I'm having this issue as well, and only with dartls. Other language servers I'm using (C#, lua, markdown, some others) don't show this issue. I haven't been able to find anything else on the internet about it.

**Comment by koga25** [comment]
From what i searched, the problem is with [dart treesitter when it idents something](https://github.com/nvim-treesitter/nvim-treesitter/issues/4945). When i was searching about this i found two temporary solutions that worked for others:

[Removing dart treesitter](https://github.com/LunarVim/LunarVim/issues/4305#issuecomment-1681451926)
[Disabling dart treesitter ident](https://github.com/NvChad/NvChad/issues/2237#issuecomment-1653019941)

I don't know if this will help you, but it doesn't hurt to try.

**Comment by arc41t3ct** [comment]
I found that always 2 processes are started dart language-server. Once I exit nvim and come back only one is running. Will also try the treesitter removal to see if that helps.

**Comment by maobai405** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/4945#issuecomment-1691168369
