### ISSUE TITLE
not working/initialize

### ISSUE THREAD

**Issue by tredeneo** [akinsho/flutter-tools.nvim#3]
the plugin not initializing automatically(LSP,Closing Tags,Outline window) then I run 

> :FlutterDevTools

I receve this error

> flutter-tools.nvim/lua/flutter-tools/dev_tools.lua:12: bad argument #1 to 'ipairs' (table expected, got number)

same result on both linux and windows

linux neovim version: 

> 0.5.0-dev+1101

windows neovim version:
> 0.5.0-dev+1099

plugin manager:
> paq-nvim

my config(init.lua):

> https://github.com/tredeneo/configs/blob/main/init.lua

**Comment by tredeneo** [comment]
I am reinstall devtools and works, but LSP not yet

**Comment by akinsho** [comment]
@tredeneo I'm away from my computer right now (on mobile). How have you got flutter set up. It's it in your PATH how did you install it? If you use falls dartls from nvim config on it's own does that work?

**Comment by tredeneo** [comment]
with dartls also not works

directory flutter on windows(where)
> C:\flutter\bin\flutter
C:\flutter\bin\flutter.bat

directory flutter on linux(whereis)
> flutter: /snap/bin/flutter.openurl 
 /snap/bin/flutter.dart  
/snap/bin/flutter

after create issue, I have installed dart-sdk(also not works)

directory dart on linux(whereis)
> dart: /usr/bin/dart  
/usr/lib/dart  
/usr/lib/dart/bin/dart  
/snap/bin/dart

directory dart on windows(where)
>C:\flutter\bin\dart
C:\flutter\bin\dart.bat
C:\tools\dart-sdk\bin\dart.exe

linux PATH
>/usr/lib/dart/bin/ 
/home/tredeneo/.local/bin/ 
/home/tredeneo/.cargo/bin/ 
/snap/bin/ 
/usr/local/sbin
/usr/local/bin 
/usr/local/games 
/usr/sbin 
/usr/bin 
/usr/games 
/sbin 
/bin

windows PATH
>C:\Program Files\PowerShell\7;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\flutter\bin;C:\Program Files\PowerShell\7\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\daniel\AppData\Local\Microsoft\WindowsApps;C:\Users\daniel\AppData\Local\Programs\Microsoft VS Code\bin;C:\tools\neovim\Neovim\bin;C:\tools\dart-sdk\bin;C:\Users\daniel\AppData\Roaming\Pub\Cache\bin

**Comment by akinsho** [comment]
@tredeneo the issue on `linux` is with how `snap` install packages, there's some magic complexity in there with symlinks so it doesn't work the same with `cli` tools such as neovim using `jobstart('flutter <cmd>')` which is what this plugin does. The solution would be to overwrite the path the lsp. In the case of `snap` that would be
`echo $HOME/snap/flutter/common/flutter/bin/flutter` but you need the binary for the `lsp` server. which would be in that folder area somwhere. You would need to override the `cmd` for the language server.

regarding windows tbh I don't use windows and can't test windows so I can't explicitly support it, but if people are willing to add functionality for it and test that it works I'd be happy to merge them

**Comment by akinsho** [comment]
@tredeneo did you manage to get it working? I'm hoping to add instructions for things like `snap` to the readme

**Comment by tredeneo** [comment]
I add `$HOME/snap/flutter/common/flutter/bin/flutter` to path, and remove flutter link from /snap/bin/ (or rename for renome "any name")
on windows, not worked I think because flutter was on root directory('C:\\'), 'User\Documents\flutter' works

**Comment by luiq54** [comment]
I made it work in windows by changing this part in `lua/flutter-tools/executable.lua` to 
```lua
local M = {
  dart_bin_name = "dart.bat",
}
```
Virtual Texts, Diagnostics, Completions and outlines, all work!

**Comment by akinsho** [comment]
@luiq54 is the `dart.bat` bit necessary for all Windows users or just your setup? I haven't had other Windows users complain as far as I know, so I don't really know if I can safely change that for all Windows users or if it will break a lot of other people's setups

**Comment by luiq54** [comment]
The `bin` folder  in flutter sdk has these files 
![image](https://user-images.githubusercontent.com/51489635/135574690-2c9a9fe8-7db5-45d1-9549-fa175281d380.png)
`dart` and `flutter` are bash scripts while other two are windows batch files. It think it is necessary to use `dart.bat` in windows.
