### ISSUE TITLE
[feature] set `flutterMode` from .nvim.lua config file

### ISSUE THREAD

**Issue by momrak** [akinsho/flutter-tools.nvim#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From what I can see there is no way of specifying the run mode the app will be launched in from the `.nvim.lua` file

### Expected Behavior

In the `launch.json` vscode file you have the following option [see link](https://docs.flutter.dev/perf/ui-performance)
```
    "flutterMode": "profile"
```

This would be a nice addition

### Steps To Reproduce

Starting flutter from within neovim using one of the configs

### Environment

```Markdown
- OS: MacOs
- Flutter version: 3.16.3
- Is flutter in $PATH: yes
- neovim version: 0.9.1
```

**Comment by akinsho** [comment]
To be honest, this isn't really something that's on my radar at all and probably is on something that I personally will have time to look into maybe @sidlatau might know about this and think it's useful to add
