### ISSUE TITLE
Add herline.nvim support

### ISSUE THREAD

**Issue by Anifyuli** [akinsho/flutter-tools.nvim#321]
Hello, Mister. I have wish to you for adding statusline support for herline.nvim. I try to add statusline section but it's not show in my herline.nvim. You can see in my screenshot.

![image](https://github.com/akinsho/flutter-tools.nvim/assets/73734843/f441eda1-68ce-46ff-aa35-5cfe3bfd32ec)

Thanks for read my issue, and sorry my English

**Comment by akinsho** [comment]
@Anifyuli this plugin doesn't explicitly integrate with statusline plugins but you can in almost all such plugins use the component this plugin provides but it will be up to you to figure out how to do that for your plugin of choice. I unfortunately won't have time to walk you through that. If you read the docs for you plugin it is probably described there
