### ISSUE TITLE
[BUG]Could not found flutter-tools command

### ISSUE THREAD

**Issue by hanasa2023** [akinsho/flutter-tools.nvim#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I install the flutter-tools with lazy.nvim as my package manager.But I can't find the command in my nvim.
![240109_18h58m32s_screenshot](https://github.com/akinsho/flutter-tools.nvim/assets/144128876/ac69bad4-40b4-49ba-87f1-8fe05a4e44e6)
![240109_19h04m27s_screenshot](https://github.com/akinsho/flutter-tools.nvim/assets/144128876/ab8c448c-fc43-4462-ab3f-6f904c61947c)

### Expected Behavior

Work normally.

### Steps To Reproduce

```:FlutterRun```

### Environment

```Markdown
- OS: ArchLinux
- Flutter version:3.13.9
- Is flutter in $PATH:yes
- neovim version:v0.10.0-dev-2047+g8df374237
```

**Comment by hanasa2023** [comment]
And when I try to use my personal config for it. A error called "module  'flutter-tools' not found"happened.

**Comment by commiru** [comment]
How did you fix this?
