### ISSUE TITLE
[Help] lsp code formatter line width

### ISSUE THREAD

**Issue by ralph-bergmann** [akinsho/flutter-tools.nvim#328]
I'm new to nvim and this plugin, so maybe it is the wrong place to ask: 

Is there a way to set the line width for the LSP code formatter? I want more than the default width of 80.

**Comment by akinsho** [comment]
@ralph-bergmann there is an option in the lap settings of the plugin but as you say, the issue tracker isn't the right place for this. Unfortunately, between time constraints that I have and the other maintainers no one is around to answer these sorts of questions. I suggest having a close look at the configuration, especially the area for the LSP. Sorry I can't provide more help

**Comment by akinsho** [comment]
@ralph-bergmann there is an option in the lap settings of the plugin but as you say, the issue tracker isn't the right place for this. Unfortunately, between time constraints that I have and the other maintainers no one is around to answer these sorts of questions. I suggest having a close look at the configuration, especially the area for the LSP. Sorry I can't provide more help

**Comment by GP4cK** [comment]
Answer is here: https://github.com/nvim-flutter/flutter-tools.nvim/issues/178
