### ISSUE TITLE
Feature: adding build runner command

### ISSUE THREAD

**Issue by JordanllHarper** [akinsho/flutter-tools.nvim#337]
Currently, to build projects using build runner, we have to do this in a separate terminal window. 

I would like to be able to run this as a command!

i.e. `FlutterBuild` or `:DartBuild`

Edit: followup, it would also be nice if we could specify the `--delete-conflicting-outputs` in a configuration.

**Comment by RyanCarrier** [comment]
I doubt this will get picked up, I'm not sure it makes sense to. This is a task in your dev process not flutter in particular, I have mine setup under overseer.nvim and a make file to make things easier.

https://github.com/stevearc/overseer.nvim

**Comment by JordanllHarper** [comment]
That makes sense I guess. It feels pretty integral to the flutter process is my only thought. Builds are often run in flutter apps and so providing it makes more sense to me than not. Happy to close though and will check out overseer.

**Comment by RyanCarrier** [comment]
I'm not sure how planned this is but I know there has been talk for a while about potential compile time macros which would solve the whole build runner step regardless

https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md
