### ISSUE TITLE
[FR] Ability to set DEV LOG position

### ISSUE THREAD

**Issue by p4-k4** [akinsho/flutter-tools.nvim#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

DEV LOG is positioned right.

### Expected Behavior

It would be nice to have a config option to change that default position of the DEV LOG to either top, bottom, left or right. Also ensuring auto-scroll is maintained if set to top/bottom.

Cheers

### Steps To Reproduce

FlutterDevices -> Choose a device.

### Environment

```Markdown
- OS: MacOS 13.5.2 (22G91)
- Flutter version: Flutter 3.19.2 • channel stable
- Is flutter in $PATH: Yes
- neovim version: NVIM v0.9.5
```

**Comment by akinsho** [comment]
I'm currently not actively developing new features for this and I'm in search of new contributors. PRs welcome

**Comment by JordanllHarper** [comment]
Old issue but doing work on dev log stuff. You can set the position with the "open_cmd" in the dev_log config table. Unless you mean you want an option to specify "left" or "right" in config?

**Comment by p4-k4** [comment]
The following currently works - hoping this remains in future updates :) This launches the DEV_LOG in a bottom split.

```lua
    dev_log = {
      enabled = true,
      notify_errors = false, -- if there is an error whilst running then notify the user
      open_cmd = "botright split", -- command to use to open the log buffer
    },
```

**Comment by sidlatau** [comment]
Looks like problem was solved.
