### ISSUE TITLE
[BUG] flutter-tools in Lazy.nvim

### ISSUE THREAD

**Issue by XNeyMo** [akinsho/flutter-tools.nvim#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I followed the documentation in the README, however I am unable to use the commands in Flutter. I just copy and paste the code into the documentation, my `init.lua` is:

```
required('lazy').setup({
        ...
        {
                'akinsho/flutter-tools.nvim',
                lazy = false,
                dependencies = {
                        'nvim-lua/plenary.nvim',
                        'stevearc/dressing.nvim', -- optional for vim.ui.select
                },
                config = true,
        },

        'nvim-lua/plenary.nvim',
        'stevearc/dressing.nvim'
        ...
},
```

### Expected Behavior

Be able to use Flutter commands

### Steps To Reproduce

1. In `lazy.nvim`, add `flutter-tools.nvim`
2. Reload nvim to install `flutter-tools`
3. Error with `:FlutterRun` (E492: Not and editor command: FlutterRun)

### Environment

```Markdown
- OS: Arch Linux 6.8.5
- Flutter version: 3.19.5
- Is flutter in $PATH: yes
- neovim version: 0.9.5
```

**Comment by JordanllHarper** [comment]
Might be useful posting your full lazy  here, as there doesn't look to be anything wrong initially.
What happens if you replace your config with 
```config  = function() 
require 'flutter-tools'.setup()
end
```

**Comment by JordanllHarper** [comment]
Also just a thought, have you tried in a flutter project? Do you get the commands then?

**Comment by mbpowers** [comment]
your config works fine for me :thinking:

**Comment by erlangparasu** [comment]
This lua file works for me:

<img width="643" alt="image" src="https://github.com/akinsho/flutter-tools.nvim/assets/20636828/baf3f137-6736-4f4f-a8be-31bc838de6a9">

```lua
return {
    'akinsho/flutter-tools.nvim',
    lazy = true,
    ft = {
        "dart",
    },
    dependencies = {
        'nvim-lua/plenary.nvim',
        'stevearc/dressing.nvim' -- optional for vim.ui.select
    },
    config = true
}
```

**Comment by sidlatau** [comment]
It looks like this is not a plugin issue, closing it.

**Comment by hulk-higakijin** [comment]
I had the same issue, but running the FlutterRun command in a `.dart` file worked for me.

**Comment by deannemphos** [comment]
Still having this same issue after a few hours of tinkering on Neovim 0.10.1; none of the commands are recognized and it doesn't appear in my Lazy packages. Plenary and Dressing are loading in just fine otherwise.

**Comment by bastislack** [comment]
Just in case other people have this problem:

I am using lazyvim and I put these lines into my `lua/plugins/example.lua` file, which as the name states is actually not used.
So just creating a new file in the `plugins` directory (e.g. `lua/plugins/flutter-tools.lua`) with this content will make it work:
```dart
return {
  {
    "nvim-flutter/flutter-tools.nvim",
    lazy = false,
    dependencies = {
      "nvim-lua/plenary.nvim",
      "stevearc/dressing.nvim", -- optional for vim.ui.select
    },
    config = true,
  },
}
```
