### ISSUE TITLE
lsp-dart vs flutter-tools

### ISSUE THREAD

**Issue by mictadlo** [akinsho/flutter-tools.nvim#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
I am new to Flutter and Dart. Furthermore, I am looking for a Lightway IDE. Which one would you recommend to use:

- flutter-tools.nvim or
- [lsp-dart](https://github.com/emacs-lsp/lsp-dart)

Thank you in advance,

Mic

### Expected Behavior

Find the best ide

### Steps To Reproduce

I searched the internet and can not find a comparison.

### Environment

```Markdown
- OS:
- Flutter version:
- Is flutter in $PATH:
- neovim version:
```

**Comment by mictadlo** [comment]
P.S. Is flutter-tools compatible with:

- [SpaceVim's  Dart/Flutter implementation](https://spacevim.org/layers/lang/dart/)
- [Normalnvim's  Dart/Flutter implementation](https://github.com/search?q=repo%3ANormalNvim%2FNormalNvim%20flutter&type=code)

**Comment by mictadlo** [comment]
P.s. Does flutter-tools provide any code [snippets](Nash0x7E2/awesome-flutter-snippets)?

**Comment by IamACoomer** [comment]
Its been a month so im guessing you have figured it out by now, if you still need help react to this
