### ISSUE TITLE
Bad argument #2 to 'join'

### ISSUE THREAD

**Issue by adelarsq** [akinsho/flutter-tools.nvim#35]
On MS Windows when open Neovim always shows this error message:

<img width="788" alt="Captura de Tela 2021-05-06 às 09 32 36" src="https://user-images.githubusercontent.com/430272/117298812-2c5e6d00-ae4e-11eb-8803-9befa8b02c85.png">

Any idea about what can be?

Thanks in advance.

**Comment by akinsho** [comment]
@adelarsq thanks for reporting this. That line is now empty in the current main commit, can you update the plugin and repost what error you are seeing.

**Comment by adelarsq** [comment]
It was a problem on the plugin manager that was stuck on the update. Thanks @akinsho
