### ISSUE TITLE
LSP Inlay Hints

### ISSUE THREAD

**Issue by DartMitai** [akinsho/flutter-tools.nvim#352]
how can we enable Inlay Hints using flutter-tools?

**Comment by DartMitai** [comment]
This thing is confusing
**Warning
flutter tools does not depend on nvim-lspconfig. The two can co-exist but please ensure you do NOT configure dartls using lspconfig. It will be automatically set up by this plugin instead.**

**Comment by akinsho** [comment]
Sorry @DartMitai but this won't be a good place to ask questions. I just do not have the time or bandwidth to field this many questions across this many plugins. You'll definitely have to ask this somewhere else through the code or the readme or help documentation a bit? Or maybe someone else will pitch in a solution for you. It doesn't require any specific code to the plugin. As far as I recall inlay hints are set up in neovim
