### ISSUE TITLE
[BUG] Closing Tags/labesl not working/displaying

### ISSUE THREAD

**Issue by paulhmurray** [akinsho/flutter-tools.nvim#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't get the commented closing labels/tags to work with my current setup. I have the very basic default setup using Lazy plugin manager

### Expected Behavior

when I write a widget and a unit of code ends, I expect to see in a comment the name of that unit of code, e.g.
Container(
                    decoration: BoxDecoration(
                      color: Theme.of(context).colorScheme.primary,
                      borderRadius: BorderRadius.circular(24),
                    ), // BoxDecoration
                    padding: const EdgeInsets.all(25),
                    child: const Icon(Icons.person, size: 64),
                  ), // Container

### Steps To Reproduce

Neovim - 0.9.5
 - Build type: "Release"
Plugin:
return {
  'akinsho/flutter-tools.nvim',
  lazy = false,
  dependencies = {
    'nvim-lua/plenary.nvim',
    'stevearc/dressing.nvim', -- optional for vim.ui.select
  },
  config = true,
}

### Environment

```Markdown
- OS:Arch linux
- Flutter version:3.22.1
- Is flutter in $PATH:yes
- neovim version:0.9.5
```

### Anything else?

I'm not sure if it is relevant, I've installed Flutter sdk with snap. I'm questioning whether that was a good choice. 
All the other flutter tools seem to work really well.

**Comment by JordanllHarper** [comment]
Have you tried installing flutter via the official documentation? What is the result of that? 

Do the other features work?

**Comment by paulhmurray** [comment]
I haven't reinstalled via the official documentation. Everything else works, except closing tags. But I'm guessing it is some weird quirk thanks to snap. I'll try that and re-open if it doesn't resolve it. For now, I'll close the ticket.
