### ISSUE TITLE
How disable view type value

### ISSUE THREAD

**Issue by codehappyness** [akinsho/flutter-tools.nvim#356]
![image](https://github.com/akinsho/flutter-tools.nvim/assets/90964344/f6f93f9d-7754-42ba-aa57-28ecbb3c1b1e)
How to disable in red box. Thanks

**Comment by sidlatau** [comment]
These are inlay hints. You could check `:h lsp-inlay_hint` to configure it according to your needs.

**Comment by konstantin-mohin** [comment]
it disables it per buffer ... 
I still can not figure out how to disable it completely, 
I tried to pass capabilities

`capabilities = {
          textDocument = {
            inlayHint = nil, -- Disable inlay hint support
          },
        },
`
and disable it via lsp settings 
`settings = {
            completeFunctionCalls = true,
             dart = {
               inlayHints = {
`

nothing works ....

**Comment by felipejoribeiro** [comment]
I Want to disable this as well. This being enabled by default by the plugin is sad. Lost several hours trying to find the source of this problem.
