### ISSUE TITLE
[Question] Newlines in autocompletion?

### ISSUE THREAD

**Issue by justinmc** [akinsho/flutter-tools.nvim#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Autocomplete replacements always come in a single line.

```dart
    LayoutBuilder(builder: builder)
```

### Expected Behavior

I'd like to configure it to put each parameter on its own line.

```dart
    LayoutBuilder(
      builder: builder,
    )
```

### Steps To Reproduce

To reproduce the example given above, in a build method, type "Layo" and select the first option, "LayoutBuilder~".

### Environment

```Markdown
- OS:Debian
- Flutter version:3.22.0-35.0.pre.505
- Is flutter in $PATH:Yes
- neovim version:v0.10.0
```

### Anything else?

I'm unsure if this is something I should be able to configure at the flutter-tools level or the lsp level. Thanks for the help.

**Comment by akinsho** [comment]
@justinmc tbh I have no idea, the actual completion behaviour happens elsewhere somewhere between nvim-cmp presuming that's what you're using for completion (or whatever other plugin is managing that) or the language server. This plugin actually doesn't have any logic around completion at all other than maybe passing options to the underlying language server but it's blind to what those are.

I think if the language server says it should be expanded then I think `cmp` would try to do that, but pretty sure it wouldn't have dart specific code to expand that sort of expression

**Comment by justinmc** [comment]
Thank you, that helps me narrow down where this is coming from. I appreciate your work on flutter-tools!
