### ISSUE TITLE
[BUG] flatten() requires a list-like table

### ISSUE THREAD

**Issue by goldhan** [akinsho/flutter-tools.nvim#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

open xxx.dart
Error executing lua callback: ...Cellar/neovim/0.10.1/share/nvim/runtime/lua/vim/iter.lua:236: flatten() requires a list-like table
stack traceback:
	[C]: in function 'error'
	...Cellar/neovim/0.10.1/share/nvim/runtime/lua/vim/iter.lua:236: in function 'flatten'
	...lazy/flutter-tools.nvim/lua/flutter-tools/utils/init.lua:151: in function 'flatten'
	...lazy/flutter-tools.nvim/lua/flutter-tools/utils/path.lua:56: in function 'join'
	...lazy/flutter-tools.nvim/lua/flutter-tools/executable.lua:105: in function '_flutter_bin_from_fvm'
	...lazy/flutter-tools.nvim/lua/flutter-tools/executable.lua:116: in function 'get'
	...e/nvim/lazy/flutter-tools.nvim/lua/flutter-tools/dap.lua:23: in function 'setup'
	...share/nvim/lazy/flutter-tools.nvim/lua/flutter-tools.lua:61: in function <...share/nvim/lazy/flutter-tools.nvim/lua/flutter-tools.lua:59>

the code highlighting is not working

### Expected Behavior

1. no error
2. code highlighting is working

### Steps To Reproduce

![20240823141808_rec_](https://github.com/user-attachments/assets/7e9c22f7-5827-4f31-b6f2-881db7a93fd0)
test.dart
```
void main(List<String> args) {
  print('hello');
}
```

### Environment

```Markdown
- OS: Mac os 14.6.1 (23G93)
- Flutter version: 3.22.2
- Is flutter in $PATH: yes
- neovim version: v0.10.1
```

### Anything else?

https://github.com/akinsho/flutter-tools.nvim/commit/33538b6fbec7785451cae8ad93de3a3bfe0fa334#diff-bda204ee28992d4fd4ac79cdf8655c85902f2413c51c91bddf3ef5055141d26e
https://github.com/neovim/neovim/issues/28777
https://github.com/neovim/neovim/pull/28781

**Comment by sidlatau** [comment]
@goldhan thanks for the report and links to the issue in nvim repo! I lifted the depreciation check to nvim v0.11, this should hopefully resolve the issue.
