### ISSUE TITLE
Lsp rename,delete and create file

### ISSUE THREAD

**Issue by akinsho** [akinsho/flutter-tools.nvim#39]
Investigate whether [dart's lsp](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md) supports updating imports and renaming imports using the lsp. This was added to neovim recently for use in `nvim-jdtls`. I'd like to find out if this can also be used here.

**Comment by amitkot** [comment]
[This VSCode issue](https://github.com/Dart-Code/Dart-Code/issues/3354) might contain relevant pointers for dart's lsp support of relevant APIs.

**Comment by akinsho** [comment]
@amitkot this is already partially implemented via the LSP it turned out I didn't need to add much, it's a setting in the language server settings `renameFilesWithClasses = 'prompt'` if you add this that functionality should already work.

I added and tested it a while ago and have been using it. Just forgot to update this.
The behaviour is documented in https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md#client-workspace-configuration
