### ISSUE TITLE
Open devtools in the browser automatically

### ISSUE THREAD

**Issue by Charly6596** [akinsho/flutter-tools.nvim#49]
- Open devtools in the browser automatically whenever the server is detected (we either have `devtools_url and profiler_url` or `devtools_profiler_url` available)
- This should be configurable, add an option to opt-out

See https://github.com/akinsho/flutter-tools.nvim/pull/44#issuecomment-841721090 for more context.

**Comment by Charly6596** [comment]
@akinsho hello, I'm trying to do this one but I can't figure out how to open the browser, do you happen to know if nvim or vim has something to do that?

**Comment by akinsho** [comment]
@Charly6596 you can do this using the `open` command or `xdg-open` command so something like `vim.fn.system("xdg-open <url>")` should work. The OS will handle doing the right thing
