### ISSUE TITLE
Update README screenshots

### ISSUE THREAD

**Issue by Charly6596** [akinsho/flutter-tools.nvim#51]
It's not possible to see all the commands as shown in the picture anymore and might confuse some people
![image](https://user-images.githubusercontent.com/13708100/118401627-b2f12680-b666-11eb-9147-f7426590d992.png)

**Comment by akinsho** [comment]
@Charly6596 👍🏾 that makes sense, for screenshots I actually upload them to GH in the #18 issue then use the generated URL in the README, I'm happy to swap the current image out with one showing the right options
