### ISSUE TITLE
provide example config

### ISSUE THREAD

**Issue by RobertBrunhage** [akinsho/flutter-tools.nvim#56]
Would be nice to see an example config for how to get this up and running with Flutter.

I am personally using coc-flutter but would love to move to this, but having a hard to getting everything working, such as autocomplete, error messages and so on.

p.s. Great work and keep it up 😊

**Comment by akinsho** [comment]
Hi @RobertBrunhage thanks for the kind words. Tbh I'm not entirely sure what sort of example to add. I think maybe a lot of what you might mean is more around how neovim's native lsp works? e.g. how to configure completion with it, etc. It's different to `coc` in that the foundation is built into neovim but users need to add plugins to get more bits of functionality, whereas `coc` tries to solve all the problems in one plugin.

For example this plugin doesn't really handle completion, or error UI or UI for code actions etc (tbh neither does coc-flutter it just depends on coc itself for that), in this plugin's case that is dependent on how a user has set up neovim's lsp. Basically it requires a bit of knowledge about setting up nvim's lsp that I'm not really sure is best done here.

I can add links to other references on how to setup nvim's lsp but I don't think there's really an example I can add that won't just be a subset of the full config options in the README.

**Comment by RobertBrunhage** [comment]
That makes a lot more sense, I think just a mention regarding what you said here could be super valuable! I think a lot of people (me included) used coc-flutter before and thinking of moving to something like this.

> For example this plugin doesn't really handle completion, or error UI or UI for code actions etc (tbh neither does coc-flutter it just depends on coc itself for that), in this plugin's case that is dependent on how a user has set up neovim's lsp. Basically it requires a bit of knowledge about setting up nvim's lsp that I'm not really sure is best done here.

**Comment by akinsho** [comment]
👍🏾 I'll add a section to the intro for this plugin explaining a little bit about migrating to neovim's lsp and some links for more information as well as how this plugin differs from something like `coc-flutter`

**Comment by akinsho** [comment]
@RobertBrunhage I've added a new intro section to the README lemme know if that would have helped you initially or if there are any bits that are unclear?

**Comment by RobertBrunhage** [comment]
@akinsho That is perfect! Thanks for taking the time for it 😊

I will close the issue!
