### ISSUE TITLE
Make flutter path configurable

### ISSUE THREAD

**Issue by akinsho** [akinsho/flutter-tools.nvim#6]
Some flutter installations such as using `snap` on ubuntu don't get automatically picked up whilst running `flutter <command>` using nvim's job start. Allow a user to specify the flutter path in their config. Technically this is already possible by specifying a different command in the lsp config but make it more explicit so it can be used throughout this project

**Comment by tredeneo** [comment]
maybe try check if exist `$HOME/snap/flutter/common/flutter/bin/flutter` and execute it before default config,or one flag `bool`

**Comment by akinsho** [comment]
This is also resolved by 31d19710c5ec53c556e07bb82274058343bcddb4 which allows the user to set a path or a command to derive the path
