### ISSUE TITLE
:FlutterRun fails on windows

### ISSUE THREAD

**Issue by nazo6** [akinsho/flutter-tools.nvim#62]
Hi.
I found that `:FlutterRun` fails on windows with this error.
```
E5108: Error executing lua ...\site\pack\packer\start\plenary.nvim\lua\plenary\job.lua:400: Failed to spawn process: {
  _additional_on_exit_callbacks = {},
  _shutdown_check = <userdata 1>,
  _stderr_results = {},
  _stdout_results = {},
  _user_on_exit = <function 1>,
  _user_on_stderr = <function 2>,
  _user_on_stdout = <function 3>,
  args = { "run" },
  command = "C:\\flutter\\bin\\flutter",
  enable_handlers = true,
  enable_recording = true,
  interactive = true,
  pid = "ENOENT: no such file or directory",
  stderr = <userdata 2>,
  stdin = <userdata 3>,
  stdout = <userdata 4>,
  user_data = {},
  <metatable> = <1>{
    __index = <table 1>,
    _create_uv_options = <function 4>,
    _execute = <function 5>,
    _pipes_are_closed = <function 6>,
    _prepare_pipes = <function 7>,
    _reset = <function 8>,
    _shutdown = <function 9>,
    _stop = <function 10>,
    add_on_exit_callback = <function 11>,
    after = <function 12>,
    after_failure = <function 13>,
    after_success = <function 14>,
    and_then = <function 15>,
    and_then_on_failure = <function 16>,
    and_then_on_failure_wrap = <function 17>,
    and_then_on_success = <function 18>,
    and_then_on_success_wrap = <function 19>,
    and_then_wrap = <function 20>,
    chain = <function 21>,
    chain_status = <function 22>,
    co_wait = <function 23>,
    is_job = <function 24>,
    join = <function 25>,
    new = <function 26>,
    pid = <function 27>,
    result = <function 28>,
    send = <function 29>,
    shutdown = <function 30>,
    start = <function 31>,
    stderr_result = <function 32>,
    sync = <function 33>,
    wait = <function 34>
  }
}
```
The executable file name for flutter in windows is `flutter.bat`, but `flutter` is running, which is probably causing this problem.

**Comment by akinsho** [comment]
@nazo6 thanks for reporting this issue.

I'm not very familiar with windows so there are always likely to be some edge cases on that OS unless I get contributions/issues from windows users.

Regarding the executable name is this universal for all windows installations? If I change this for all windows users is there some type/version of windows that will break?

Do you have flutter in your $PATH? if you do this plugin should just take the path returned by vim without snipping the extension? are you setting `flutter_path` or `flutter_lookup_cmd`?

**Comment by nazo6** [comment]
I found out that the problem was caused by `resolve(exepath("flutter"))` returning a path without extension, but when I tried it with vanilla neovim, it returned the correct path with extension. It seems to be a problem with my configuration, so I'm closing this issue.
Thanks for making such a great plugin!
