### ISSUE TITLE
Add the ability to change the highlight groups.

### ISSUE THREAD

**Issue by ashishbinu** [akinsho/flutter-tools.nvim#63]
I would like to change the colors for this notification window using highlight groups. Is there some highlight groups that i can achieve to do that.

![image](https://user-images.githubusercontent.com/56691622/124154423-1ae2bb80-dab3-11eb-963a-44cac0fcfabe.png)

**Comment by akinsho** [comment]
@ashishbinu the plugins highlights are inherited from your nvim configurations/colorschemes highlights
In this case it is using `FloatBorder` and `NormalFloat` I would check what you have set those values to and tweaking them should allow you to control how these windows are coloured.

**Comment by ashishbinu** [comment]
> @ashishbinu the plugins highlights are inherited from your nvim configurations/colorschemes highlights
> In this case it is using `FloatBorder` and `NormalFloat` I would check what you have set those values to and tweaking them should allow you to control how these windows are coloured.

I tried changing the background and forefground of the text using `NormalFloat` but it doesn't seem to change it. It changed the floating windows color in packer though.

**Comment by akinsho** [comment]
@ashishbinu it depends on when you are trying to make this change are you setting the value of `NormalFloat` before this plugin is loaded. Can you check the value of `:verbose highlight NormalFloat` and paste it here? I've tweaked this highlight in my config, and it works as expected

**Comment by ashishbinu** [comment]
@akinsho 
![image](https://user-images.githubusercontent.com/56691622/124169718-2f7b7f80-dac4-11eb-8a3c-c1a9f4a714a2.png)
This is what the command says about the NormalFloat

![image](https://user-images.githubusercontent.com/56691622/124169630-11158400-dac4-11eb-9fa4-7090fa7736e4.png)
This is where I have added the highlights to NormalFloat. 

It also highlights other stuff too...Even it worked , how can I only limit it to that notification only.

**Comment by akinsho** [comment]
@ashishbinu I've linked you in a PR, can you please try that branch. FWIW, you are applying the highlighting too late in your example, you have applied the highlight *after* loading the plugin.

**Comment by akinsho** [comment]
fixed by #64
