### ISSUE TITLE
code action like coc-flutter?

### ISSUE THREAD

**Issue by shaeinst** [akinsho/flutter-tools.nvim#72]
is it possible to warp or extract widget like [coc-flutter](https://github.com/theniceboy/coc-flutter-tools#code-actions)?

**Comment by barun108** [comment]
Yes , I am using this tool with LunarVim , 
It works good for Live Reload, and Code actions like 'Wrap with widget ' etc ...

I am still working to set up supports feature

**Comment by shaeinst** [comment]
what's special about LunarVim? isn't LuarVim is just a configs with many plugin? and how LunarVim is achieving this feature?

**Comment by akinsho** [comment]
@shaeinst I cover this in the README under the `New to Neovim LSP` section. Basically as the section mentions you have to set up code actions and autocomplete using other plugins since this is not specific to dart or flutter.

I recommend looking at `lspsaga` or a new plugin I'm personally using is [`lsp-fastaction.nvim`](https://github.com/windwp/lsp-fastaction.nvim)

**Comment by akinsho** [comment]
If you want a minimal solution please look at `:h vim.lsp.buf.code_action`

**Comment by barun108** [comment]
> @shaeinst I cover this in the README under the `New to Neovim LSP` section. Basically as the section mentions you have to set up code actions and autocomplete using other plugins since this is not specific to dart or flutter.
> 
> I recommend looking at `lspsaga` or a new plugin I'm personally using is [`lsp-fastaction.nvim`](https://github.com/windwp/lsp-fastaction.nvim)

Hey @akinsho 

Since LunarVim team has integrated your plugin in their configuration, 

Can you write(Update ReadMe) a LunarVim specific setup guide ?

**Comment by shaeinst** [comment]
@akinsho sorry but i still didn't get how to setup this. can you please write/paste the code? i am not have very good understanding of n(vim). may be this would help others in future

**Comment by akinsho** [comment]
@barun108 tbh I don't really want to advocate any specific configuration pack or anything like that. I definitely don't want to have to figure out LunarVim's config and have to keep up to date with it. The *only* reason I'm even mentioning any new plugins at all is just to facilitate redirecting people in the future I want to remove links to other plugins that aren't integrated in this plugin

**Comment by akinsho** [comment]
@shaeinst just giving you some random snippet of code is probably not going to work.

I don't know what your setup is, how you've configured your nvim or much about your setup at all. The README of lspsaga gives quite a good amount of detail about how to set it up. You *have to* read the documentation for these plugins.

The most minimal code action example for code actions is which should work for anyone using nvim's lsp client
```vim
nnoremap <leader>ca <Cmd>lua vim.lsp.buf.code_action()<CR>
```

**Comment by akinsho** [comment]
I'm going to close this now, as I've listed examples of plugins in the README and shown some minimal examples to boot. Given this isn't actually directly related to this plugin, I don't think there's more to do.

**Comment by MitaiDart** [comment]
> я лично использую, это [`lsp-fastaction.nvim`](https://github.com/windwp/lsp-fastaction.nvim)

still using it? I didn't understand where to insert this code
```
--- add this to your mapping on lsp
    vim.api.nvim_buf_set_keymap(
        bufnr,
        'n',
        '<leader>a',
        '<cmd>lua require("lsp-fastaction").code_action()<CR>'
    )
    vim.api.nvim_buf_set_keymap(
        bufnr,
        'v',
        '<leader>a',
        "<esc><cmd>lua require('lsp-fastaction').range_code_action()<CR>",
    )```
