### ISSUE TITLE
[Question]  best integreted with external snippet `vsnip`

### ISSUE THREAD

**Issue by ayoubelmhamdi** [akinsho/flutter-tools.nvim#78]
i'm use 
```
akinsho/flutter-tools.nvim
hrsh7th/vim-vsnip
Neevash/awesome-flutter-snippets
```
 for snippet and lsp ,  because i cant use `lsp` only for build widget as `StatefulWidget` ,  
but i can't now use `vsnip` and this plugin `akinsho/flutter-tools.nvim` ,   
because `lsp` give me ton of suggestion at the end i see `vsnip` suggestion  
 - how i can handle `snippet/lsp`
 - why i cant use snippet of widget   from lsp without snippet

**Comment by akinsho** [comment]
@ayoubelmhamdi so completion and snippets are handled entirely outside this plugin using nvim-compe or something. If you are using nvim-compe if you read through its documentation, you'll find that there's a priority option you can set for each source, so you can make vsnip higher priority.

As for the specific questions you ask, I'm sorry but I don't understand
>   how i can handle snippet/lsp
    why i cant use snippet of widget from lsp without snippet

FWiW this issue also doesn't include any information about your setup, so I wouldn't be able to help, if there was an issue relating to this plugin

**Comment by ayoubelmhamdi** [comment]
@akinsho  , yes i use 'hrsh7th/nvim-compe' and i change now priority of `vsnip` .it's view on top but not very good experience  
but still lsp can do better , for auto create statefullw and statelessW ...

**Comment by akinsho** [comment]
@ayoubelmhamdi I'm sorry, but I really don't understand. This plugin is not related to completion or snippets, these are handled in other plugins. If you are encountering issues with either, can you please raise those in the appropriate repositories.

**Comment by ayoubelmhamdi** [comment]
yah, i forget , you don't responsible for lsp  suggestions :`dart-analyser` 
thank you for help
