### ISSUE TITLE
Closing labels - change font?

### ISSUE THREAD

**Issue by shivahnshankar** [akinsho/flutter-tools.nvim#82]
I am using iTerm and Fira Code (Bold). However, the closing labels are also in bold and are quite distracting.
Can you please share how you managed to get the closing labels in your config?
Thanks

**Comment by akinsho** [comment]
@shivahnshankar the closing labels use the same highlight as the your `Comment` highlight group. It seems in your case your comment highlight is bold which is why your labels are bold. You can tweak the highlight group in your config with something like `highlight Comment guifg=<my-hex> gui=NONE`

**Comment by akinsho** [comment]
Alteratively you can set the preferred highlight group in your config using
```lua
  -- rest of config
  closing_tags = {
    highlight = "ErrorMsg", -- highlight for the closing tag
  },
```

**Comment by shivahnshankar** [comment]
The theme that I was using was indeed not setting up the Comment highlight properly. It is working great with doom-one theme now.
Thanks!
