### ISSUE TITLE
[Question]: FlutterRun logs in new tab

### ISSUE THREAD

**Issue by ldelossa** [akinsho/flutter-tools.nvim#85]
Hello,

Is it possible to open up the log window when calling `FlutterRun` in a new tab?

**Comment by akinsho** [comment]
@ldelossa yes it is, there is open command which can be changed to any vim file open command like `vsplit`, `edit` or in your case `tabedit`
```lua
  dev_log = {
	 open_cmd = 'tabedit'
  },
```

**Comment by barungh** [comment]
> @ldelossa yes it is, there is open command which can be changed to any vim file open command like `vsplit`, `edit` or in your case `tabedit`
> 
> ```lua
>   dev_log = {
> 	 open_cmd = 'tabedit'
>   },
> ```

Useful

**Comment by ldelossa** [comment]
Thanks a lot! Closing.

**Comment by zeina99** [comment]
How can I change it so that it opens in a new tmux window? is that possible?

**Comment by akinsho** [comment]
@zeina99 that's not possible that sounds quite complex not sure I'd provide that sort of functionality out of the box

**Comment by zeina99** [comment]
Oh okay! 

Thank you for the great plugin btw, its very helpful.
