### ISSUE TITLE
__flutter_tools_select_device is nil when selecting device

### ISSUE THREAD

**Issue by solidassassin** [akinsho/flutter-tools.nvim#86]
**Describe the bug**

Plugin is trying to call `__flutter_tools_select_device` even tho looking at the source it's not added to the global namespace (`_G`), let alone defined anywhere.

```
E5108: Error executing lua [string ":lua"]:1: attempt to call global '__flutter_tools_select_device' (a nil value)
```

**To Reproduce**

1. Enter `:FlutterRun`
2. Select device
3. See error

This can be easily avoided by passing the device arg to `FlutterRun`, just thought it be nice to know.

**Comment by akinsho** [comment]
Hi @solidassassin thanks for reporting this 👍🏿 it's the result of a slightly messy refactor. I've just pushed what I hope is a fix in the latest commit on main let me know if that fixes things for you

**Comment by solidassassin** [comment]
You sure you're not getting an error [here](https://github.com/akinsho/flutter-tools.nvim/blob/main/lua/flutter-tools/commands.lua#L80)?

Afaik the function doesn't support passing lua functions directly (you need to use lua strings).

**Comment by akinsho** [comment]
Ah sorry tbh I'm on holiday should just leave the fix till I'm free, I can't actually test these changes properly. That function should probably use `utils.map`

**Comment by solidassassin** [comment]
No problems, like I said: *just to let you know*.

**Comment by akinsho** [comment]
@solidassassin this should now *actually* be fixed, so I'm going to optimistically close this, but if you are still getting issues let me know or just re-open this issue.

**Comment by solidassassin** [comment]
Sorry for the silence, works like a charm, thanks :+1:
