### ISSUE TITLE
[Question] Cannot find flutter binary to start lsp

### ISSUE THREAD

**Issue by oboingo** [akinsho/flutter-tools.nvim#88]
I am having a similar issue to:
https://github.com/akinsho/flutter-tools.nvim/issues/53

When running :FlutterOutlineOpen or :FlutterOutlineToggle, on a Flutter file, with Widgets in it... I get:
Sorry!  There is no outline for this file.

When I start a new instance of nvim with a Flutter file, I get a:
Client 1 quit with exit code 255 and signal 0

:FlutterRun, :FlutterDevices, and others work properly.

My config is:

```
      use {'akinsho/flutter-tools.nvim', 
            requires = 'nvim-lua/plenary.nvim',
            config = function() 
                require("flutter-tools").setup{
                    experimental = { -- map of feature flags
                        lsp_derive_paths = true -- experimental: Attempt to find the user's flutter SDK
                    },
                    debugger = { -- integrate with nvim dap + install dart code debugger
                        enabled = true,
                    },  
                    dev_tools = {
                        autostart = true, -- autostart devtools server if not detected
                        auto_open_browser = true, -- Automatically opens devtools in the browser
                    },
                    outline = {
                        open_cmd = "30vnew", -- command to use to open the outline buffer
                        auto_open = true -- if true this will open the outline automatically when it is first populated
                    },
                }
            end
        }
```

Flutter doctor shows:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] Connected device (3 available)

• No issues found!
```

:LspInfo shows attached clients for other filetypes, but not for Dart.

I have also tried setting flutter_path to the value of 'flutter sdk-path' manually and it didn't work either.  I don't have lsp enabled for Dart anywhere else, but lsp is working for other languages (like Python).  

Clearly I have done something wrong, but I don't know what.  Can you provide any insights into where I should look?  Are there logs I can look at somewhere?  Thanks in advance for any help you can provide, I appreciate it.

**Comment by akinsho** [comment]
Hi @oboingo, this probably relates to where/how flutter is installed on your system. Can you clarify how you installed it? Does the `flutter sdk-path` command exist on your system. The error you're seeing means that the lsp isn't getting started correctly. Also, FYI, You should not be using `lsp_derive_paths` if you didn't install flutter via `snap` btw.

**Comment by oboingo** [comment]
I installed it via Snap.  The `flutter sdk-path` seems to work fine and points to ~/snap/flutter/common/flutter

**Comment by akinsho** [comment]
@oboingo is nvim installed via snap as well? I recently tried installed nvim that way and found that it had a lot of little bugs including the nvim binary not being able to launch the lsp whereas it works whilst installed using the ppa

**Comment by oboingo** [comment]
I used the appimage install method.

**Comment by akinsho** [comment]
@oboingo can you check what the lsp logs show. You can do this by checking the value of `vim.lsp.get_log_path()` this will tell you where the log is saved. Once you have that can you open the file and see if there are any error logs printed.

This error is a common one but one I can't help with since it will have to do with something about how your lsp is setup on your machine. Does your app image have sufficient permissions to run processes in the snap directory?

**Comment by oboingo** [comment]
Thank you for your help which helped me to get it working much better.

In case anyone else searches for this, the error  I was getting was:
`[ ERROR ] 2021-08-19T17:37:52-0700 ] ...nt_nvimo1pcXe/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]  "rpc"   "dart"  "stderr"        "Wrong full snapshot version, expected 'b555f636e5ed67c4cd65ec7250ff2930' found 'e4a09dbf2bb120fe4674e0576617a0dc'\n"`

It took a few tries of various things, and eventually a quick uninstall of Flutter and dart, and a reinstall of Flutter and it all works now.  Thanks again for your help in the right direction.  Your tip of the log location was especially helpful.  (Perhaps you should put that in the documentation to help others?)
