### ISSUE TITLE
[Question] how to pass environment variables?

### ISSUE THREAD

**Issue by marcusatiliusregulus** [akinsho/flutter-tools.nvim#89]
if the shell exports environment variables all works fine.
for example if CHROME_EXECUTABLE is set `:FlutterDevices` does list my browser.
however if i want to pass variables via the vim config instead of the shell it doesnt work -
`FlutterDevices` does not list my browser.

```
require('flutter-tools').setup{
    lsp = {
        cmd_env = {CHROME_EXECUTABLE = "/usr/bin/chromium"} 
    }
}
```

**Comment by akinsho** [comment]
Hi @marcusatiliusregulus tbh I don't really do that, If I have an env variable I want to add I usually add it via my shell. There are quite a lot of different jobs this plugin starts, so not really sure of what a general way to pass env vars not in your shell env would be. What are you trying to pass the env variable to?

**Comment by marcusatiliusregulus** [comment]
i just wanted flutter-doctor/:FlutterDevices to find my chromium installation. as i usually only take my vim config with me, not my shell config too, i wanted to set it here... but if its not possible, ill just have to remember to export the var...
